# -*- coding: utf-8 -*-
"""aplicacion

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u6eDxzU520Gqa0I63XVV9StafY--8xie
"""

import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
import statsmodels.api as sm
from io import BytesIO
import warnings
from datetime import datetime, timedelta
from typing import Dict, Any, List

# Ocultar advertencias de Streamlit y Pandas
warnings.filterwarnings('ignore')
st.set_option('deprecation.showPyplotGlobalUse', False)

# ==============================================================================
# 1. CONFIGURACIÓN INICIAL Y CONSTANTES GLOBALES
# ==============================================================================

st.set_page_config(
    page_title="Horizonte Empresarial 360 - Acuamar S.A.",
    page_icon="🌊",
    layout="wide",
    initial_sidebar_state="expanded"
)

# --- Constantes de Negocio (Globales) ---
UMBRAL_LIQUIDEZ_MINIMA = 0.0 # Umbral para la alerta de Cash Flow
TASA_IVA_GENERAL = 0.19
TASA_IMPUESTO_RENTA = 0.35
TASA_RETENCION_FUENTE = 0.025
TASA_ROTACION_CARTERA_DIAS = 30 # Días de rotación de cartera
HORIZONTE_PROYECCION_DEFAULT = 12 # Meses de proyección por defecto
NUM_SIMULACIONES_DEFAULT = 5000 # Número de simulaciones de Monte Carlo

# Factores Ambientales (Para Huella de Carbono)
EF_COMBUSTIBLE = 2.68  # Kg CO2e/L
EF_ELECTRICO = 0.20    # Kg CO2e/kWh
DIAS_TRABAJO_ANUAL = 240 # Para cálculo de Indicadores HSEQ

MODULOS = [
    "Dashboard General",
    "Módulo Gobernanza y Dueños",
    "Módulo Financiero",
    "Módulo Sostenibilidad Social RRHH",
    "Módulo Sostenibilidad Ambiental",
    "Módulo Riesgos HSEQ",
    "Módulo Comercial",
    "Módulo Operativo (Productividad)"
]

# ==============================================================================
# 2. AUTENTICACIÓN Y SEGURIDAD (Simulación)
# ==============================================================================

def check_password():
    """Retorna `True` si el usuario ingresó la contraseña correcta."""

    def password_entered():
        """Verifica si la contraseña es correcta."""
        if (st.session_state["username"] == "usuario_demo" and
            st.session_state["password"] == "demo360"):
            st.session_state["password_correct"] = True
            del st.session_state["password"]  # Eliminar para seguridad
            del st.session_state["username"]
        else:
            st.session_state["password_correct"] = False

    if "password_correct" not in st.session_state:
        # Primera ejecución, muestra la entrada de contraseña.
        st.title("🌊 Horizonte Empresarial 360")
        st.info("Acceso restringido. Por favor, ingrese sus credenciales.")
        col1, col2 = st.columns(2)
        with col1:
            st.text_input("Usuario", key="username")
        with col2:
            st.text_input("Contraseña", type="password", on_change=password_entered, key="password")
        return False
    elif not st.session_state["password_correct"]:
        # Contraseña incorrecta, muestra el mensaje de error.
        st.error("😕 Usuario o Contraseña incorrectos.")
        col1, col2 = st.columns(2)
        with col1:
            st.text_input("Usuario", key="username")
        with col2:
            st.text_input("Contraseña", type="password", on_change=password_entered, key="password")
        return False
    else:
        # Contraseña correcta.
        return True

# ==============================================================================
# 3. CARGA DE DATOS Y PRE-PROCESAMIENTO
# ==============================================================================

@st.cache_data
def load_data_from_upload(uploaded_files: List[Any]) -> Dict[str, pd.DataFrame]:
    """Carga y pre-procesa todos los DataFrames necesarios desde archivos XLSX."""

    # Mapeo de nombre de hoja a variable de sesión y nombre de columna de FECHA
    data_map_sheet_to_info = {
        'financiero': {'var': 'df_financiero', 'date_col': 'FECHA'},
        'comercial': {'var': 'df_comercial', 'date_col': 'FECHA_TRANSACCION'},
        'rrhh_social': {'var': 'df_rrhh', 'date_col': 'FECHA'},
        'sostenibilidad': {'var': 'df_sostenibilidad', 'date_col': 'Fecha_Reporte'},
        'riesgos_hseq': {'var': 'df_riesgos', 'date_col': 'FECHA'},
        'productividad': {'var': 'df_operativo', 'date_col': 'FECHA'}, # Asumiendo 'productividad' es el nombre de la hoja
    }

    loaded_data = {}
    st.sidebar.markdown("---")
    st.sidebar.subheader("Estado de Carga de Datos")

    for file in uploaded_files:
        try:
            xls = pd.ExcelFile(file)
            for sheet_name in xls.sheet_names:
                map_info = None
                # Buscar la información de mapeo para el nombre de la hoja (insensible a mayúsculas/minúsculas)
                for k, v in data_map_sheet_to_info.items():
                    if k.lower() == sheet_name.lower():
                        map_info = v
                        break

                if map_info is None:
                    st.sidebar.info(f"⏭️ Saltando hoja '{sheet_name}' en '{file.name}' (no reconocida o no necesaria).")
                    continue

                df = pd.read_excel(xls, sheet_name=sheet_name)

                # Conversión de fechas
                if map_info['date_col'] in df.columns:
                    df[map_info['date_col']] = pd.to_datetime(df[map_info['date_col']], errors='coerce')

                # Renombrar columna de fecha a un estándar 'FECHA' para consistencia
                df.rename(columns={map_info['date_col']: 'FECHA'}, inplace=True)

                # Pre-procesamiento específico
                if map_info['var'] == 'df_comercial':
                    df['Ingreso_Total'] = df['Volumen_Vendido'] * df['Precio_Unitario_Real']
                    df['Costo_Total'] = df['Volumen_Vendido'] * df['Costo_Venta_Unitario']
                    df['Margen_Bruto'] = df['Ingreso_Total'] - df['Costo_Total']

                if map_info['var'] == 'df_sostenibilidad':
                    # Calcular Huella de Carbono (Alcance 1: Combustible, Alcance 2: Electricidad)
                    df['CO2e_Combustible'] = df['Consumo_Combustible_ACPM'] * EF_COMBUSTIBLE if 'Consumo_Combustible_ACPM' in df.columns else 0
                    df['CO2e_Electrico'] = df['Consumo_Electrico_kWh'] * EF_ELECTRICO if 'Consumo_Electrico_kWh' in df.columns else 0
                    df['Huella_CO2e_Total'] = df['CO2e_Combustible'] + df['CO2e_Electrico']

                if map_info['var'] == 'df_riesgos':
                    # Calcular Costo Total por Evento HSEQ
                    df.rename(columns={'Costo_Total_Evento': 'Costo_Total_Accidente'}, inplace=True)

                if map_info['var'] == 'df_rrhh':
                    # Calcular Costo por FTE (Full-Time Equivalent)
                    df['Costo_x_FTE'] = df['Costo_Total_Nomina'] / df['FTEs_Promedio'] if 'Costo_Total_Nomina' in df.columns and 'FTEs_Promedio' in df.columns and df['FTEs_Promedio'].sum() > 0 else 0

                if map_info['var'] == 'df_operativo':
                    # Calcular OEE (Overall Equipment Effectiveness) - Simplificado
                    # Asegurarse de que Horas_Operadas.mean() no sea cero para evitar division por cero
                    mean_horas_operadas = df['Horas_Operadas'].mean()
                    df['OEE_Teorico'] = (df['Unidades_Producidas'] / (df['Horas_Disponibles'] * (df['Unidades_Producidas'].mean() / mean_horas_operadas))).clip(upper=1.0) if mean_horas_operadas > 0 else 0
                    df['Tasa_Defectos'] = df['Unidades_Defectuosas'] / df['Unidades_Producidas'] if 'Unidades_Defectuosas' in df.columns and 'Unidades_Producidas' in df.columns and df['Unidades_Producidas'].sum() > 0 else 0
                    df['Costo_Total_Reproceso'] = df['Unidades_Defectuosas'] * df['Costo_Reproceso_Unit'] if 'Unidades_Defectuosas' in df.columns and 'Costo_Reproceso_Unit' in df.columns else 0

                # Guardar el DataFrame
                loaded_data[map_info['var']] = df
                st.sidebar.success(f"✅ Cargado: {map_info['var'].replace('df_', '').upper()} (desde hoja '{sheet_name}' de '{file.name}')")

        except Exception as e:
            st.sidebar.error(f"❌ Error al cargar/procesar el archivo '{file.name}' o alguna de sus hojas: {e}")

    # Verificar que todos los DataFrames requeridos estén presentes
    required_dfs = ['df_financiero', 'df_comercial', 'df_rrhh', 'df_sostenibilidad', 'df_riesgos', 'df_operativo']
    for df_name in required_dfs:
        if df_name not in loaded_data:
            loaded_data[df_name] = pd.DataFrame() # DataFrame vacío si falta

    return loaded_data


# ==============================================================================
# 4. FUNCIONES DE CÁLCULO Y VISUALIZACIÓN POR MÓDULO
# ==============================================================================

# --- Módulo de Gobernanza y Dueños ---
def display_gobernanza_module(all_dfs: Dict[str, pd.DataFrame]):
    st.title("👑 Módulo Gobernanza y Dueños")
    st.subheader("Visión Estratégica y Health Score")

    df_financiero = all_dfs.get('df_financiero')
    df_sostenibilidad = all_dfs.get('df_sostenibilidad')
    df_riesgos = all_dfs.get('df_riesgos')
    df_rrhh = all_dfs.get('df_rrhh')

    st.markdown("""
        Este módulo consolida el rendimiento de la organización en un *Health Score* integral para la toma de decisiones al más alto nivel.
    """)

    # Inicializar variables KPI con valores predeterminados seguros
    ingresos = 0.0
    margen_neto_op = 0.0
    huella_co2_total = 0.0
    cumplimiento_ambiental = 0.0
    avg_rotacion = 0.0
    indice_gravedad = 0.0
    health_score = 0.0
    latest_date_str = "N/A"

    # Bandera para verificar si todos los datos mínimos están presentes para el Health Score
    can_calculate_health_score = True

    if not df_financiero.empty and 'FECHA' in df_financiero.columns and \
       not df_sostenibilidad.empty and 'Incumplimientos_Vencidos' in df_sostenibilidad.columns and 'Huella_CO2e_Total' in df_sostenibilidad.columns and \
       not df_riesgos.empty and 'Dias_Perdidos' in df_riesgos.columns and 'Horas_Trabajadas_Periodo' in df_riesgos.columns and \
       not df_rrhh.empty and 'Tasa_Rotacion_Anual' in df_rrhh.columns:

        latest_date_str = df_financiero['FECHA'].max().strftime('%Y-%m')

        # Indicador Financiero
        last_fin = df_financiero.loc[df_financiero['FECHA'].idxmax()]
        ingresos = last_fin.get('Ventas_Gravadas', 0.0)
        egresos_operativos = last_fin.get('Gastos_Gravados', 0.0) + last_fin.get('Gasto_Nomina', 0.0)
        margen_neto_op = ingresos - egresos_operativos

        # Indicador Ambiental (Cumplimiento y Huella)
        num_incumplimientos = df_sostenibilidad['Incumplimientos_Vencidos'].sum()
        max_posible_incumplimientos = df_sostenibilidad.shape[0] * 4 # Maximo 4 por mes (ejemplo)
        cumplimiento_ambiental = 1 - (num_incumplimientos / max_posible_incumplimientos) if max_posible_incumplimientos > 0 else 1
        huella_co2_total = df_sostenibilidad['Huella_CO2e_Total'].sum()

        # Indicador Social (Rotación)
        avg_rotacion = df_rrhh['Tasa_Rotacion_Anual'].mean() / 100 # Promedio histórico

        # Indicador Riesgos (Índice de Gravedad)
        total_dias_perdidos = df_riesgos['Dias_Perdidos'].sum()
        total_horas_trabajadas = df_riesgos['Horas_Trabajadas_Periodo'].sum()
        indice_gravedad = (total_dias_perdidos / total_horas_trabajadas) * 240000 if total_horas_trabajadas > 0 else 0

        # Simulación de Health Score (0 a 100)
        score_financiero = min(100, max(0, (margen_neto_op / (ingresos * 0.15)) * 50)) if ingresos > 0 else 0 # Basado en 15% de margen como meta
        score_ambiental = cumplimiento_ambiental * 100
        score_social = min(100, max(0, (1 - (avg_rotacion / 0.18)) * 100)) # Basado en 18% de rotación como máximo
        score_riesgos = min(100, max(0, (1 - (indice_gravedad / 50)) * 100)) # Basado en 50 como índice de gravedad máxima

        health_score = (score_financiero * 0.35 + score_ambiental * 0.25 + score_social * 0.20 + score_riesgos * 0.20)

    else:
        st.warning("No hay datos cargados para generar el Health Score o faltan DataFrames/columnas clave (Financiero, Sostenibilidad, Riesgos, RRHH). Asegúrese de cargar todos los archivos requeridos.")
        can_calculate_health_score = False

    st.subheader("Indicadores Clave Consolidados (Último Periodo)")
    st.caption(f"Datos consolidados hasta: {latest_date_str}")

    col1, col2, col3, col4, col5 = st.columns(5)

    col1.metric("Ingresos Último Mes", f"COP {ingresos:,.0f}", delta_color="normal")
    col2.metric("Margen Operativo", f"COP {margen_neto_op:,.0f}", delta_color="normal")
    col3.metric("Huella CO2e Acumulada", f"{huella_co2_total:,.0f} Kg", delta_color="inverse")
    col4.metric("Tasa de Rotación Anual (Promedio)", f"{avg_rotacion*100:.2f}%", delta_color="inverse")
    col5.metric("Índice de Gravedad HSEQ", f"{indice_gravedad:.2f}", delta_color="inverse")

    st.markdown("---")
    st.subheader("🎯 Health Score Empresarial 360")
    st.metric("Health Score General", f"{health_score:.1f}/100",
              help="Índice ponderado basado en el rendimiento financiero, ambiental, social y de riesgos.")

    if can_calculate_health_score: # Solo mostrar el gráfico si se pudo calcular el score
        fig = go.Figure(go.Indicator(
            mode = "gauge+number",
            value = health_score,
            domain = {'x': [0, 1], 'y': [0, 1]},
            title = {'text': "Health Score Empresarial"},
            gauge = {'axis': {'range': [None, 100], 'tickwidth': 1, 'tickcolor': "darkblue"},
                     'bar': {'color': "green"},
                     'steps': [
                         {'range': [0, 50], 'color': "red"},
                         {'range': [50, 75], 'color': "yellow"},
                         {'range': [75, 100], 'color': "green"}],
                     'threshold': {'line': {'color': "red", 'width': 4}, 'thickness': 0.75, 'value': 75}}))

        st.plotly_chart(fig, use_container_width=True)
    else:
        st.info("El Health Score no se puede calcular debido a la falta de datos clave.")


# --- Módulo Financiero ---
def display_financiero_module(df_financiero: pd.DataFrame, HORIZONTE_PROYECCION: int, NUM_SIMULACIONES: int):
    st.title("💰 Módulo Financiero: Gestión de Liquidez y Cash Flow")
    st.subheader("Proyección de Flujo de Caja (Cash Flow)")

    if df_financiero.empty or 'FECHA' not in df_financiero.columns or \
       'Cobros_Clientes' not in df_financiero.columns or 'Pagos_Proveedores' not in df_financiero.columns or \
       'Gasto_Nomina' not in df_financiero.columns or 'Efectivo_Inicial' not in df_financiero.columns:
        st.warning("No se encontraron datos financieros completos. Por favor, cargue el archivo `financiero.xlsx` con todas las columnas requeridas.")
        return

    # 1. Configuración de Simulación
    st.markdown("---")
    with st.expander("⚙️ Configuración de Escenarios de Proyección"):
        st.info("La proyección usa la media histórica y la desviación estándar de los flujos de caja (Cobros y Pagos) para simular el riesgo (Método Monte Carlo).")
        st.caption("Ajuste los parámetros del simulador:")

        # Inputs para el usuario
        col1, col2 = st.columns(2)
        with col1:
            cobros_ajuste = st.number_input("Ajuste de Cobros (% sobre media histórica)", min_value=-50, max_value=50, value=0, help="Ajusta la media de Cobros. Ej: 5 para un escenario optimista (+5%).")
        with col2:
            pagos_ajuste = st.number_input("Ajuste de Pagos (% sobre media histórica)", min_value=-50, max_value=50, value=0, help="Ajusta la media de Pagos. Ej: -5 para un escenario optimista en costos (-5%).")

    # 2. Análisis Histórico de Flujos
    df_financiero = df_financiero.sort_values('FECHA').copy()
    df_financiero['Flujo_Neto'] = df_financiero['Cobros_Clientes'] - (df_financiero['Pagos_Proveedores'] + df_financiero['Gasto_Nomina'])

    # Calcular Efectivo_Final de manera robusta
    df_financiero['Efectivo_Final'] = df_financiero['Efectivo_Inicial'] + df_financiero['Flujo_Neto']

    st.subheader("Análisis Histórico de Efectivo")
    col_hist1, col_hist2 = st.columns(2)

    flujo_neto_promedio = df_financiero['Flujo_Neto'].mean() if not df_financiero.empty else 0.0
    efectivo_final_ultimo_periodo = 0.0

    if df_financiero.shape[0] >= 2 and 'Efectivo_Final' in df_financiero.columns:
        efectivo_final_ultimo_periodo = df_financiero['Efectivo_Final'].iloc[-2] # El penúltimo es el último 'final' antes de la proyección
    elif df_financiero.shape[0] == 1 and 'Efectivo_Final' in df_financiero.columns: # Si solo hay un registro, ese es el último
         efectivo_final_ultimo_periodo = df_financiero['Efectivo_Final'].iloc[-1]


    col_hist1.metric("Flujo Neto Promedio Mensual", f"COP {flujo_neto_promedio:,.0f}")
    col_hist2.metric("Efectivo Final (Último Periodo)", f"COP {efectivo_final_ultimo_periodo:,.0f}")

    # Gráfico Histórico
    if not df_financiero.empty:
        fig_hist = px.line(df_financiero.tail(24), x='FECHA', y=['Cobros_Clientes', 'Pagos_Proveedores', 'Gasto_Nomina'],
                           title='Tendencia Histórica de Flujos de Caja (Últimos 2 Años)',
                           labels={'value': 'COP', 'FECHA': 'Fecha', 'variable': 'Tipo de Flujo'})
        fig_hist.update_layout(hovermode="x unified", legend_title_text='Flujo')
        st.plotly_chart(fig_hist, use_container_width=True)
    else:
        st.info("No hay suficientes datos históricos para mostrar la tendencia de flujos de caja.")

    # 3. Simulación de Monte Carlo (Flujo de Caja Proyectado)

    # Estadísticas para la simulación
    flujo_neto_mean = df_financiero['Flujo_Neto'].mean() if not df_financiero.empty else 0.0
    flujo_neto_std = df_financiero['Flujo_Neto'].std() if not df_financiero.empty else 0.0

    # Ajuste de la media según el input del usuario
    ajuste_factor = (1 + (cobros_ajuste / 100)) - (1 + (pagos_ajuste / 100))
    flujo_neto_mean_ajustado = flujo_neto_mean * (1 + ajuste_factor / 2) # Ajuste simple

    # Punto de partida de la simulación
    start_date = df_financiero['FECHA'].max() + pd.DateOffset(months=1) if not df_financiero.empty else datetime.now()
    effective_start_cash = 0.0 # Reinicializar para la simulación
    if df_financiero.shape[0] > 0 and 'Efectivo_Final' in df_financiero.columns:
        effective_start_cash = df_financiero['Efectivo_Final'].iloc[-1]

    st.subheader(f"Simulación de {NUM_SIMULACIONES} Escenarios a {HORIZONTE_PROYECCION} Meses")

    df_sim = pd.DataFrame() # Initialize df_sim
    if df_financiero.shape[0] > 0 and 'Efectivo_Final' in df_financiero.columns:
        try:
            simulations = []
            for _ in range(NUM_SIMULACIONES):
                # Generar variaciones mensuales (Normal Distribution)
                monthly_flows = np.random.normal(loc=flujo_neto_mean_ajustado, scale=flujo_neto_std, size=HORIZONTE_PROYECCION)

                # Calcular el flujo acumulado
                cash_flow_projection = [effective_start_cash]
                for flow in monthly_flows:
                    cash_flow_projection.append(cash_flow_projection[-1] + flow)

                simulations.append(cash_flow_projection[1:])

            df_sim = pd.DataFrame(simulations).T
            df_sim.columns = [f'Sim_{i+1}' for i in range(NUM_SIMULACIONES)]

            # Creación de fechas de proyección
            projected_dates = [start_date + pd.DateOffset(months=i) for i in range(HORIZONTE_PROYECCION)]
            df_sim['FECHA'] = projected_dates
            df_sim = df_sim.set_index('FECHA')

            # Cálculo de percentiles
            df_sim['Media'] = df_sim.mean(axis=1)
            df_sim['P5'] = df_sim.quantile(0.05, axis=1)  # Escenario Pesimista
            df_sim['P95'] = df_sim.quantile(0.95, axis=1) # Escenario Optimista

            # Gráfico de Proyección
            fig_proj = go.Figure()

            # Bandas de confianza (Percentiles 5 y 95)
            fig_proj.add_trace(go.Scatter(x=df_sim.index, y=df_sim['P95'], fill=None, mode='lines',
                                          line_color='rgba(0,176,246,0.3)', name='Percentil 95% (Optimista)'))
            fig_proj.add_trace(go.Scatter(x=df_sim.index, y=df_sim['P5'], fill='tonexty', mode='lines',
                                          line_color='rgba(255,160,0,0.3)', name='Percentil 5% (Pesimista)'))

            # Línea de Media
            fig_proj.add_trace(go.Scatter(x=df_sim.index, y=df_sim['Media'], mode='lines',
                                          line=dict(color='blue', width=2), name='Proyección Media'))

            # Umbral de Liquidez Mínima
            fig_proj.add_hline(y=UMBRAL_LIQUIDEZ_MINIMA, line_width=2, line_dash="dash", line_color="red",
                               annotation_text=f"Umbral de Alerta ({UMBRAL_LIQUIDEZ_MINIMA:,.0f} COP)", annotation_position="bottom right")

            fig_proj.update_layout(title=f'Proyección de Efectivo Final a {HORIZONTE_PROYECCION} Meses',
                                   yaxis_title='Efectivo (COP)', xaxis_title='Mes de Proyección',
                                   hovermode="x unified")
            st.plotly_chart(fig_proj, use_container_width=True)

            # 4. Conclusión de Riesgo
            risk_months = df_sim[df_sim['P5'] <= UMBRAL_LIQUIDEZ_MINIMA].shape[0]
            if risk_months > 0:
                st.error(f"🚨 ALERTA DE RIESGO: El Escenario Pesimista (P5) predice que el Efectivo Final caerá por debajo del umbral de liquidez mínima (COP {UMBRAL_LIQUIDEZ_MINIMA:,.0f}) en {risk_months} de los {HORIZONTE_PROYECCION} meses proyectados. Se recomienda aplicar estrategias de gestión de capital de trabajo y cobranza.")
            else:
                st.success("✅ La proyección de liquidez es saludable. El Escenario Pesimista (P5) se mantiene por encima del umbral de alerta.")

        except Exception as e:
            st.error(f"Error al ejecutar la simulación de Monte Carlo: {e}")
            st.info("Asegúrese de que las columnas `Cobros_Clientes`, `Pagos_Proveedores`, y `Gasto_Nomina` sean numéricas y no contengan valores nulos significativos.")
    else:
        st.info("No hay datos financieros suficientes para realizar la simulación de Monte Carlo.")

    # 5. Descarga de Reporte
    st.markdown("---")
    def create_pdf_report(df: pd.DataFrame) -> BytesIO:
        """Simulación de generación de reporte PDF (usa CSV como placeholder)."""
        output = BytesIO()
        # En una aplicación real, usarías ReportLab o FPDF para generar un PDF.
        # Aquí, generamos el DF de simulación como CSV para la descarga.
        df.to_csv(output, index=True)
        output.seek(0)
        return output

    if not df_sim.empty and all(col in df_sim.columns for col in ['Media', 'P5', 'P95']): # Check if df_sim was successfully created and has expected columns
        report_buffer = create_pdf_report(df_sim[['Media', 'P5', 'P95']])
        st.download_button(
            label="Descargar Reporte de Proyección Financiera (CSV)",
            data=report_buffer,
            file_name="Reporte_Proyeccion_Cash_Flow.csv",
            mime="text/csv"
        )
    else:
        st.info("No hay datos de simulación disponibles para descargar el reporte.")

# --- Módulo de Sostenibilidad Social RRHH ---
def display_rrhh_module(df_rrhh: pd.DataFrame):
    st.title("👨‍👩‍👧‍👦 Módulo Sostenibilidad Social y RRHH")

    if df_rrhh.empty or 'FECHA' not in df_rrhh.columns or 'FTEs_Promedio' not in df_rrhh.columns or 'Tasa_Rotacion_Anual' not in df_rrhh.columns or 'Costo_x_FTE' not in df_rrhh.columns or 'Inversion_Capacitacion' not in df_rrhh.columns:
        st.warning("No se encontraron datos de RRHH completos. Por favor, cargue el archivo `rrhh_social.xlsx` con todas las columnas requeridas.")
        return

    # 1. Indicadores Clave
    st.subheader("Indicadores Clave de Talento")

    latest_date = df_rrhh['FECHA'].max()
    latest_data = df_rrhh[df_rrhh['FECHA'] == latest_date].iloc[0]

    col1, col2, col3, col4 = st.columns(4)
    col1.metric("FTEs Promedio (Último Periodo)", f"{latest_data['FTEs_Promedio']:.1f}")
    col2.metric("Tasa de Rotación Anual", f"{latest_data['Tasa_Rotacion_Anual']:.2f}%", delta_color="inverse")
    col3.metric("Costo por FTE (Último Periodo)", f"COP {latest_data['Costo_x_FTE']:,.0f}")
    col4.metric("Inversión en Capacitación (Acumulada)", f"COP {df_rrhh['Inversion_Capacitacion'].sum():,.0f}")

    # 2. Análisis de Tendencia
    st.subheader("Tendencia de Rotación vs. Inversión en Capacitación")

    fig1 = px.line(df_rrhh.sort_values('FECHA'), x='FECHA', y='Tasa_Rotacion_Anual',
                   title='Tasa de Rotación Anual por Mes',
                   labels={'Tasa_Rotacion_Anual': 'Tasa de Rotación (%)', 'FECHA': 'Fecha'})
    st.plotly_chart(fig1, use_container_width=True)

    fig2 = px.bar(df_rrhh.sort_values('FECHA'), x='FECHA', y='Inversion_Capacitacion',
                  title='Inversión Mensual en Capacitación',
                  labels={'Inversion_Capacitacion': 'Inversión (COP)', 'FECHA': 'Fecha'})
    st.plotly_chart(fig2, use_container_width=True)

    # 3. Distribución de Costo por FTE
    st.subheader("Distribución de Costo Total de Nómina")

    fig3 = px.histogram(df_rrhh, x='Costo_x_FTE', nbins=20,
                        title='Distribución de Costo por FTE a lo largo del tiempo',
                        labels={'Costo_x_FTE': 'Costo por FTE (COP)'})
    st.plotly_chart(fig3, use_container_width=True)


# --- Módulo de Sostenibilidad Ambiental ---
def display_sostenibilidad_ambiental_module(df_sostenibilidad: pd.DataFrame):
    st.title("🌳 Módulo Sostenibilidad Ambiental")
    st.subheader("Monitoreo de Huella y Cumplimiento")

    if df_sostenibilidad.empty or 'FECHA' not in df_sostenibilidad.columns or 'Huella_CO2e_Total' not in df_sostenibilidad.columns or \
       'Consumo_Agua_Total_m3' not in df_sostenibilidad.columns or 'Kg_Residuos_Solidos' not in df_sostenibilidad.columns or \
       'Costo_Multa_Ambiental' not in df_sostenibilidad.columns or 'Consumo_Combustible_ACPM' not in df_sostenibilidad.columns or \
       'Consumo_Electrico_kWh' not in df_sostenibilidad.columns or 'Descarga_DBO5_Kg' not in df_sostenibilidad.columns or \
       'Incumplimientos_Vencidos' not in df_sostenibilidad.columns:
        st.warning("No se encontraron datos de Sostenibilidad Ambiental completos. Por favor, cargue el archivo `sostenibilidad.xlsx` con todas las columnas requeridas.")
        return

    df = df_sostenibilidad.sort_values('FECHA').copy()

    # 1. Indicadores Clave
    st.subheader("Métricas de Impacto Ambiental")

    total_co2 = df['Huella_CO2e_Total'].sum()
    total_agua = df['Consumo_Agua_Total_m3'].sum()
    total_residuos = df['Kg_Residuos_Solidos'].sum()
    total_multa = df['Costo_Multa_Ambiental'].sum()

    col1, col2, col3, col4 = st.columns(4)
    col1.metric("Huella CO2e Total (Kg)", f"{total_co2:,.0f}", delta_color="inverse")
    col2.metric("Consumo Agua Total (m³)", f"{total_agua:,.0f} m³", delta_color="inverse")
    col3.metric("Residuos Sólidos (Kg)", f"{total_residuos:,.0f} Kg", delta_color="inverse")
    col4.metric("Costo Acumulado Multas", f"COP {total_multa:,.0f}", delta_color="inverse")

    # 2. Huella de Carbono por Alcance (Gráfico de torta/sol)
    st.subheader("Huella de Carbono (Alcance 1 y 2)")

    co2_alcance = pd.DataFrame({
        'Alcance': ['Alcance 1 (Combustible)', 'Alcance 2 (Electricidad)'],
        'CO2e': [df['CO2e_Combustible'].sum(), df['CO2e_Electrico'].sum()]
    })

    fig_co2 = px.pie(co2_alcance, values='CO2e', names='Alcance',
                     title='Distribución de Huella de Carbono (Kg CO2e)',
                     color_discrete_sequence=px.colors.sequential.Agsunset)
    st.plotly_chart(fig_co2, use_container_width=True)

    # 3. Tendencia de Consumos Críticos
    st.subheader("Tendencia de Consumos y Descargas de DBO5")

    fig_cons = px.line(df, x='FECHA', y=['Consumo_Combustible_ACPM', 'Consumo_Electrico_kWh', 'Consumo_Agua_Total_m3'],
                       title='Consumo de Recursos (Mensual)',
                       labels={'value': 'Unidad de Consumo', 'variable': 'Recurso', 'FECHA': 'Fecha'})
    fig_cons.add_trace(go.Bar(x=df['FECHA'], y=df['Descarga_DBO5_Kg'], name='Descarga DBO5 (Kg)', yaxis='y2', opacity=0.3))

    fig_cons.update_layout(yaxis=dict(title="Consumo (L/kWh/m³)", side="left"),
                           yaxis2=dict(title="DBO5 (Kg)", overlaying="y", side="right"),
                           legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1))
    st.plotly_chart(fig_cons, use_container_width=True)

    # 4. Impacto Financiero de Incumplimiento
    st.subheader("Costo de Multas y Número de Incumplimientos Vencidos")

    fig_multa = px.bar(df, x='FECHA', y='Costo_Multa_Ambiental',
                       title='Costo Mensual por Multas Ambientales',
                       labels={'Costo_Multa_Ambiental': 'Costo (COP)', 'FECHA': 'Fecha'})
    fig_multa.add_trace(go.Scatter(x=df['FECHA'], y=df['Incumplimientos_Vencidos'], mode='lines+markers',
                                   name='Incumplimientos Vencidos', yaxis='y2', line=dict(color='red')))

    fig_multa.update_layout(yaxis=dict(title="Costo Multa (COP)", side="left"),
                           yaxis2=dict(title="Incumplimientos Vencidos", overlaying="y", side="right"),
                           hovermode="x unified")
    st.plotly_chart(fig_multa, use_container_width=True)


# --- Módulo Riesgos HSEQ ---
def display_riesgos_hseq_module(df_riesgos: pd.DataFrame):
    st.title("🚨 Módulo Riesgos HSEQ (Salud, Seguridad, Ambiente y Calidad)")
    st.subheader("Monitoreo de Incidentes y Cumplimiento Normativo")

    if df_riesgos.empty or 'FECHA' not in df_riesgos.columns or 'Tipo_Evento' not in df_riesgos.columns or \
       'Horas_Trabajadas_Periodo' not in df_riesgos.columns or 'Dias_Perdidos' not in df_riesgos.columns or \
       'Costo_Total_Accidente' not in df_riesgos.columns or 'Estado_Checklist' not in df_riesgos.columns:
        st.warning("No se encontraron datos de Riesgos HSEQ completos. Por favor, cargue el archivo `riesgos_hseq.xlsx` con todas las columnas requeridas.")
        return

    df = df_riesgos.sort_values('FECHA').copy()

    # Cálculos HSEQ Clásicos (Tasa de Frecuencia y Severidad)
    total_incidentes = df[df['Tipo_Evento'] == 'Accidente Laboral'].shape[0]
    total_horas = df['Horas_Trabajadas_Periodo'].sum()
    total_dias_perdidos = df['Dias_Perdidos'].sum()

    # Tasa de Frecuencia (IF) = (Total Incidentes / Horas Trabajadas) * 240,000
    indice_frecuencia = (total_incidentes / total_horas) * 240000 if total_horas > 0 else 0
    # Tasa de Severidad (IS) = (Días Perdidos / Horas Trabajadas) * 240,000
    indice_severidad = (total_dias_perdidos / total_horas) * 240000 if total_horas > 0 else 0

    # 1. Indicadores Clave de Riesgo
    st.subheader("Índices de Seguridad y Salud en el Trabajo")

    col1, col2, col3, col4 = st.columns(4)
    col1.metric("Total Incidentes (Accidentes)", f"{total_incidentes:,}")
    col2.metric("Índice de Frecuencia (IF)", f"{indice_frecuencia:.2f}", help="Incidentes por 240,000 horas hombre")
    col3.metric("Índice de Severidad (IS)", f"{indice_severidad:.2f}", delta_color="inverse", help="Días perdidos por 240,000 horas hombre")
    col4.metric("Costo Total Acumulado Incidentes", f"COP {df['Costo_Total_Accidente'].sum():,.0f}", delta_color="inverse")

    # 2. Clasificación de Eventos
    st.subheader("Distribución de Eventos de Riesgo")

    event_counts = df['Tipo_Evento'].value_counts().reset_index()
    event_counts.columns = ['Tipo_Evento', 'Conteo']

    fig_event = px.bar(event_counts, x='Tipo_Evento', y='Conteo',
                       title='Conteo por Tipo de Evento (Accidente, Incumplimiento, No Conformidad)',
                       labels={'Conteo': 'Número de Eventos', 'Tipo_Evento': 'Tipo de Evento'},
                       color='Tipo_Evento', color_discrete_sequence=px.colors.qualitative.Bold)
    st.plotly_chart(fig_event, use_container_width=True)

    # 3. Cumplimiento Normativo (Checklist)
    st.subheader("Estado de Cumplimiento de Checklists Normativos")

    cumplimiento = df['Estado_Checklist'].value_counts().reset_index()
    cumplimiento.columns = ['Estado', 'Conteo']

    fig_comp = px.pie(cumplimiento, values='Conteo', names='Estado',
                      title='Porcentaje de Checklists HSEQ',
                      color_discrete_map={'Cumplido': 'green', 'Pendiente': 'yellow', 'Vencido': 'red'})
    st.plotly_chart(fig_comp, use_container_width=True)


# --- Módulo Comercial ---
def display_comercial_module(df_comercial: pd.DataFrame):
    st.title("📈 Módulo Comercial: Gestión de Ventas y Margen")

    if df_comercial.empty or 'FECHA' not in df_comercial.columns or 'Ingreso_Total' not in df_comercial.columns or \
       'Margen_Bruto' not in df_comercial.columns or 'Volumen_Vendido' not in df_comercial.columns:
        st.warning("No se encontraron datos comerciales completos. Por favor, cargue el archivo `comercial.xlsx` con todas las columnas requeridas.")
        return

    # 1. Indicadores Clave
    st.subheader("Métricas de Venta y Rentabilidad")

    total_ingresos = df_comercial['Ingreso_Total'].sum()
    total_margen_bruto = df_comercial['Margen_Bruto'].sum()
    margen_bruto_pct = (total_margen_bruto / total_ingresos) * 100 if total_ingresos > 0 else 0

    col1, col2, col3, col4 = st.columns(4)
    col1.metric("Ingreso Total (Acumulado)", f"COP {total_ingresos:,.0f}")
    col2.metric("Margen Bruto Total", f"COP {total_margen_bruto:,.0f}")
    col3.metric("Margen Bruto (%)", f"{margen_bruto_pct:.2f}%")
    col4.metric("Total de Transacciones", f"{df_comercial.shape[0]:,}")

    # 2. Análisis Temporal de Margen
    df_mensual = df_comercial.set_index('FECHA').resample('M').agg({
        'Ingreso_Total': 'sum',
        'Margen_Bruto': 'sum',
        'Volumen_Vendido': 'sum'
    }).reset_index()
    df_mensual['Margen_Bruto_Pct'] = (df_mensual['Margen_Bruto'] / df_mensual['Ingreso_Total']) * 100 if not df_mensual['Ingreso_Total'].empty and df_mensual['Ingreso_Total'].sum() > 0 else 0

    st.subheader("Tendencia de Margen Bruto Mensual")
    fig1 = px.area(df_mensual, x='FECHA', y='Margen_Bruto_Pct',
                   title='Margen Bruto Porcentual a lo largo del Tiempo',
                   labels={'Margen_Bruto_Pct': 'Margen Bruto (%)', 'FECHA': 'Fecha'})
    st.plotly_chart(fig1, use_container_width=True)

    # 3. Top 10 Productos por Margen
    st.subheader("Top 10 Productos por Margen Bruto")
    if 'Producto_ID' in df_comercial.columns and 'Margen_Bruto' in df_comercial.columns:
        top_productos = df_comercial.groupby('Producto_ID')['Margen_Bruto'].sum().nlargest(10).reset_index()
        fig2 = px.bar(top_productos, x='Margen_Bruto', y='Producto_ID', orientation='h',
                      title='Top 10 Productos por Margen Bruto Acumulado',
                      labels={'Margen_Bruto': 'Margen Bruto (COP)', 'Producto_ID': 'ID Producto'})
        fig2.update_yaxes(categoryorder='total ascending')
        st.plotly_chart(fig2, use_container_width=True)
    else:
        st.info("No hay datos de productos suficientes para mostrar el Top 10 por Margen Bruto.")


# --- Módulo Operativo (Productividad/Procesos) ---
def display_operativo_module(df_operativo: pd.DataFrame):
    st.title("🏭 Módulo Operativo (Productividad y Procesos)")

    if df_operativo.empty or 'FECHA' not in df_operativo.columns or 'OEE_Teorico' not in df_operativo.columns or \
       'Tasa_Defectos' not in df_operativo.columns or 'Costo_Total_Reproceso' not in df_operativo.columns or \
       'Horas_Operadas' not in df_operativo.columns or 'Unidades_Defectuosas' not in df_operativo.columns or \
       'Costo_Mano_Obra_Hora' not in df_operativo.columns or 'Planta_ID' not in df_operativo.columns:
        st.warning("No se encontraron datos operativos completos. Por favor, cargue el archivo `productividad.xlsx` con todas las columnas requeridas.")
        return

    # 1. Indicadores Clave
    st.subheader("Métricas de Eficiencia de Producción")

    # Métricas Operativas
    avg_oee = df_operativo['OEE_Teorico'].mean() * 100 if not df_operativo.empty else 0.0
    avg_tasa_defectos = df_operativo['Tasa_Defectos'].mean() * 100 if not df_operativo.empty else 0.0
    total_costo_reproceso = df_operativo['Costo_Total_Reproceso'].sum() if not df_operativo.empty else 0.0
    total_horas_operadas = df_operativo['Horas_Operadas'].sum() if not df_operativo.empty else 0.0

    col1, col2, col3, col4 = st.columns(4)
    col1.metric("OEE Promedio (Teórico)", f"{avg_oee:.2f}%", delta_color="normal", help="Eficiencia General del Equipo - Simplificado.")
    col2.metric("Tasa Promedio de Defectos", f"{avg_tasa_defectos:.2f}%", delta_color="inverse")
    col3.metric("Costo Acumulado de Reproceso", f"COP {total_costo_reproceso:,.0f}", delta_color="inverse")
    col4.metric("Horas Operadas Totales", f"{total_horas_operadas:,.0f} h")

    # 2. OEE y Tasa de Defectos
    st.subheader("Tendencia de Eficiencia y Calidad")

    df_operativo['Mes_Año'] = df_operativo['FECHA'].dt.to_period('M').astype(str)

    fig1 = go.Figure()
    fig1.add_trace(go.Scatter(x=df_operativo['Mes_Año'], y=df_operativo['OEE_Teorico'] * 100, mode='lines+markers', name='OEE (%)', yaxis='y1'))
    fig1.add_trace(go.Scatter(x=df_operativo['Mes_Año'], y=df_operativo['Tasa_Defectos'] * 100, mode='lines+markers', name='Tasa de Defectos (%)', yaxis='y2', line=dict(color='red')))

    fig1.update_layout(
        title='OEE y Tasa de Defectos a lo Largo del Tiempo',
        xaxis_title='Fecha',
        yaxis=dict(title="OEE (%)", side="left", range=[0, 100]),
        yaxis2=dict(title="Tasa de Defectos (%)", overlaying="y", side="right", range=[0, df_operativo['Tasa_Defectos'].max()*100*1.1 if not df_operativo['Tasa_Defectos'].empty else 10])
    )
    st.plotly_chart(fig1, use_container_width=True)


    # 3. Reproceso vs. Costo
    st.subheader("Costo de Reproceso vs. Unidades Defectuosas")

    fig2 = px.scatter(df_operativo, x='Unidades_Defectuosas', y='Costo_Total_Reproceso',
                      size='Costo_Mano_Obra_Hora', color='Planta_ID', hover_name='FECHA',
                      title='Relación entre Defectos y Costo de Reproceso (Tamaño: Costo Mano de Obra)')
    st.plotly_chart(fig2, use_container_width=True)

# --- Dashboard General ---
def display_dashboard(all_dfs: Dict[str, pd.DataFrame]):
    st.title("🌐 Dashboard General: Visión 360")
    st.subheader("Resumen de Métricas Clave de la Plataforma")

    st.markdown("""
        Este dashboard ofrece una perspectiva de alto nivel del rendimiento de **Acuamar S.A.**,
        consolidando los KPIs más críticos de los 7 módulos.
    """)

    # Extraer métricas clave para el Dashboard
    metrics = {}

    # Módulo Financiero
    df_financiero = all_dfs.get('df_financiero')
    if not df_financiero.empty and 'Ventas_Gravadas' in df_financiero.columns and 'Gastos_Gravados' in df_financiero.columns and 'Gasto_Nomina' in df_financiero.columns and 'Efectivo_Inicial' in df_financiero.columns:
        last_fin = df_financiero.loc[df_financiero['FECHA'].idxmax()] if 'FECHA' in df_financiero.columns else pd.Series()
        ingresos = last_fin.get('Ventas_Gravadas', 0.0)
        egresos_operativos = last_fin.get('Gastos_Gravados', 0.0) + last_fin.get('Gasto_Nomina', 0.0)
        metrics['Margen_Neto_Op'] = ingresos - egresos_operativos
        metrics['Efectivo_Final'] = df_financiero['Efectivo_Inicial'].iloc[-1] if not df_financiero.empty else 0.0
    else:
        metrics['Margen_Neto_Op'] = 0.0
        metrics['Efectivo_Final'] = 0.0

    # Módulo Comercial
    df_comercial = all_dfs.get('df_comercial')
    if not df_comercial.empty and 'Ingreso_Total' in df_comercial.columns and 'Margen_Bruto' in df_comercial.columns:
        total_ingresos = df_comercial['Ingreso_Total'].sum()
        total_margen_bruto = df_comercial['Margen_Bruto'].sum()
        metrics['Margen_Bruto_Pct'] = (total_margen_bruto / total_ingresos) * 100 if total_ingresos > 0 else 0
    else:
        metrics['Margen_Bruto_Pct'] = 0.0

    # Módulo Social (RRHH)
    df_rrhh = all_dfs.get('df_rrhh')
    if not df_rrhh.empty and 'Tasa_Rotacion_Anual' in df_rrhh.columns and 'FTEs_Promedio' in df_rrhh.columns:
        metrics['Rotacion_Anual'] = df_rrhh['Tasa_Rotacion_Anual'].iloc[-1] if not df_rrhh.empty else 0.0
        metrics['FTEs'] = df_rrhh['FTEs_Promedio'].iloc[-1] if not df_rrhh.empty else 0.0
    else:
        metrics['Rotacion_Anual'] = 0.0
        metrics['FTEs'] = 0.0

    # Módulo Ambiental
    df_sostenibilidad = all_dfs.get('df_sostenibilidad')
    if not df_sostenibilidad.empty and 'Huella_CO2e_Total' in df_sostenibilidad.columns and 'Costo_Multa_Ambiental' in df_sostenibilidad.columns:
        metrics['Huella_CO2e_Total'] = df_sostenibilidad['Huella_CO2e_Total'].sum()
        metrics['Costo_Multas'] = df_sostenibilidad['Costo_Multa_Ambiental'].sum()
    else:
        metrics['Huella_CO2e_Total'] = 0.0
        metrics['Costo_Multas'] = 0.0

    # Módulo Riesgos HSEQ
    df_riesgos = all_dfs.get('df_riesgos')
    if not df_riesgos.empty and 'Tipo_Evento' in df_riesgos.columns and 'Horas_Trabajadas_Periodo' in df_riesgos.columns:
        total_incidentes = df_riesgos[df_riesgos['Tipo_Evento'] == 'Accidente Laboral'].shape[0]
        total_horas = df_riesgos['Horas_Trabajadas_Periodo'].sum()
        metrics['IF_HSEQ'] = (total_incidentes / total_horas) * 240000 if total_horas > 0 else 0
    else:
        metrics['IF_HSEQ'] = 0.0

    # Módulo Operativo
    df_operativo = all_dfs.get('df_operativo')
    if not df_operativo.empty and 'OEE_Teorico' in df_operativo.columns and 'Tasa_Defectos' in df_operativo.columns:
        metrics['OEE_Promedio'] = df_operativo['OEE_Teorico'].mean() * 100
        metrics['Tasa_Defectos'] = df_operativo['Tasa_Defectos'].mean() * 100
    else:
        metrics['OEE_Promedio'] = 0.0
        metrics['Tasa_Defectos'] = 0.0

    # 1. Row de Indicadores de Alto Nivel
    st.header("1. Rendimiento Global")
    col1, col2, col3, col4 = st.columns(4)
    col1.metric("💰 Margen Neto Operativo", f"COP {metrics.get('Margen_Neto_Op', 0):,.0f}", help="Ingresos - Egresos Operativos")
    col2.metric("📈 Margen Bruto Comercial (%)", f"{metrics.get('Margen_Bruto_Pct', 0):.2f}%")
    col3.metric("🏭 OEE Promedio", f"{metrics.get('OEE_Promedio', 0):.2f}%", delta_color="normal")
    col4.metric("👨‍👩‍👧‍👦 Rotación Anual (Últ. Mes)", f"{metrics.get('Rotacion_Anual', 0):.2f}%", delta_color="inverse")

    # 2. Row de Indicadores de Riesgo y Sostenibilidad
    st.header("2. Riesgos y Sostenibilidad")
    col5, col6, col7, col8 = st.columns(4)
    col5.metric("🚨 Índice Frecuencia HSEQ (IF)", f"{metrics.get('IF_HSEQ', 0):.2f}", delta_color="inverse")
    col6.metric("🌳 Huella CO2e (Acumulada)", f"{metrics.get('Huella_CO2e_Total', 0):,.0f} Kg", delta_color="inverse")
    col7.metric("💧 Costo Multas Ambientales", f"COP {metrics.get('Costo_Multas', 0):,.0f}", delta_color="inverse")
    col8.metric("📉 Tasa Promedio de Defectos", f"{metrics.get('Tasa_Defectos', 0):.2f}%", delta_color="inverse")

    # 3. Gráfico de Tendencia Integrada
    st.header("3. Tendencias Financieras y Operativas")

    if not df_financiero.empty and 'FECHA' in df_financiero.columns and 'Flujo_Neto' in df_financiero.columns and \
       not df_operativo.empty and 'FECHA' in df_operativo.columns and 'OEE_Teorico' in df_operativo.columns:
        # Preparar datos para gráfico de línea dual
        df_fin_mensual = df_financiero.set_index('FECHA')['Flujo_Neto'].resample('M').sum().reset_index()
        df_op_mensual = df_operativo.set_index('FECHA')['OEE_Teorico'].resample('M').mean().reset_index()

        df_merge = pd.merge(df_fin_mensual, df_op_mensual, on='FECHA', how='inner')

        if not df_merge.empty:
            fig_trend = go.Figure()

            # Flujo Neto (Eje Y1)
            fig_trend.add_trace(go.Bar(x=df_merge['FECHA'], y=df_merge['Flujo_Neto'], name='Flujo Neto (COP)', yaxis='y1', opacity=0.6))

            # OEE (Eje Y2)
            fig_trend.add_trace(go.Scatter(x=df_merge['FECHA'], y=df_merge['OEE_Teorico'] * 100, mode='lines+markers', name='OEE (%)', yaxis='y2', line=dict(color='green', width=3)))

            fig_trend.update_layout(
                title='Relación: Flujo Neto (Finanzas) vs. OEE (Operaciones)',
                xaxis_title='Fecha',
                yaxis=dict(title="Flujo Neto (COP)", side="left"),
                yaxis2=dict(title="OEE (%)", overlaying="y", side="right", range=[0, 100]),
                legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1)
            )
            st.plotly_chart(fig_trend, use_container_width=True)
        else:
            st.info("No hay datos combinados suficientes para mostrar la tendencia financiera y operativa.")
    else:
        st.info("No hay datos financieros u operativos suficientes para mostrar la tendencia integrada.")


# ==============================================================================
# 5. FLUJO PRINCIPAL DE LA APLICACIÓN
# ==============================================================================

if check_password():

    # Carga de archivos al inicio de la sesión
    if 'data_loaded' not in st.session_state:
        st.session_state['data_loaded'] = False
        st.session_state['dfs'] = {}
        st.session_state['HORIZONTE_PROYECCION'] = HORIZONTE_PROYECCION_DEFAULT
        st.session_state['NUM_SIMULACIONES'] = NUM_SIMULACIONES_DEFAULT

    st.sidebar.markdown("---")

    # Sección de Carga de Archivos
    with st.sidebar.expander("📂 Cargar Datos"):
        st.caption("Cargue todos los archivos .xlsx requeridos. Puede subir varios archivos Excel, y el sistema buscará las hojas correspondientes por nombre (financiero, comercial, rrhh_social, sostenibilidad, riesgos_hseq, productividad).")
        uploaded_files = st.file_uploader(
            "Arrastre y suelte los archivos .xlsx aquí",
            type=['xlsx'],
            accept_multiple_files=True
        )
        if uploaded_files:
            # Botón de carga y procesamiento (solo se ejecuta si hay archivos y no se ha cargado)
            if st.button("Procesar Archivos Cargados"):
                st.session_state['dfs'] = load_data_from_upload(uploaded_files)
                st.session_state['data_loaded'] = True
                st.success("¡Datos cargados y pre-procesados con éxito!")

    # Placeholder de Conexión SQL
    st.sidebar.markdown("---")
    st.sidebar.subheader("Conexión a Datos Vivos (Simulado)")
    st.sidebar.success("Estado: Conectado a SQL DB (Simulación)")

    st.sidebar.markdown("---")
    st.sidebar.subheader("Navegación por Módulos")

    # Selector de módulo en el sidebar
    selected_module = st.sidebar.radio("Selecciona un Módulo", MODULOS)

    # Slider de Horizonte de Proyección para Módulos Predictivos
    st.sidebar.markdown("---")
    st.session_state['HORIZONTE_PROYECCION'] = st.sidebar.slider(
        "Horizonte de Proyección (Meses)",
        min_value=3, max_value=24,
        value=st.session_state['HORIZONTE_PROYECCION'],
        step=1
    )
    st.session_state['NUM_SIMULACIONES'] = st.sidebar.slider(
        "Número de Simulaciones (Monte Carlo)",
        min_value=1000, max_value=10000,
        value=st.session_state['NUM_SIMULACIONES'],
        step=1000
    )


    # Contenido central basado en el módulo seleccionado
    if not st.session_state['data_loaded']:
        st.title("Bienvenido a Horizonte Empresarial 360")
        st.info("Por favor, cargue los archivos de datos en la sección 'Cargar Datos' del menú lateral para comenzar a navegar por los módulos.")
    else:
        dfs = st.session_state['dfs']

        if selected_module == "Dashboard General":
            display_dashboard(dfs)

        elif selected_module == "Módulo Gobernanza y Dueños":
            display_gobernanza_module(dfs)

        elif selected_module == "Módulo Financiero":
            display_financiero_module(dfs['df_financiero'], st.session_state['HORIZONTE_PROYECCION'], st.session_state['NUM_SIMULACIONES'])

        elif selected_module == "Módulo Sostenibilidad Social RRHH":
            display_rrhh_module(dfs['df_rrhh'])

        elif selected_module == "Módulo Sostenibilidad Ambiental":
            display_sostenibilidad_ambiental_module(dfs['df_sostenibilidad'])

        elif selected_module == "Módulo Riesgos HSEQ":
            display_riesgos_hseq_module(dfs['df_riesgos'])

        elif selected_module == "Módulo Comercial":
            display_comercial_module(dfs['df_comercial'])

        elif selected_module == "Módulo Operativo (Productividad)":
            display_operativo_module(dfs['df_operativo'])