{
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/Pamela-Data-Analyst/Horizonte_Empresarial360/blob/main/main.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "import streamlit as st\n",
        "import pandas as pd\n",
        "import numpy as np\n",
        "import plotly.express as px\n",
        "import plotly.graph_objects as go\n",
        "import statsmodels.api as sm\n",
        "from io import BytesIO\n",
        "import warnings\n",
        "from datetime import datetime, timedelta\n",
        "from typing import Dict, Any, List\n",
        "\n",
        "# Ocultar advertencias de Streamlit y Pandas\n",
        "warnings.filterwarnings('ignore')\n",
        "st.set_option('deprecation.showPyplotGlobalUse', False)\n",
        "\n",
        "# ==============================================================================\n",
        "# 1. CONFIGURACIÓN INICIAL Y CONSTANTES GLOBALES\n",
        "# ==============================================================================\n",
        "\n",
        "st.set_page_config(\n",
        "    page_title=\"Horizonte Empresarial 360 - Acuamar S.A.\",\n",
        "    page_icon=\"🌊\",\n",
        "    layout=\"wide\",\n",
        "    initial_sidebar_state=\"expanded\"\n",
        ")\n",
        "\n",
        "# --- Constantes de Negocio (Globales) ---\n",
        "UMBRAL_LIQUIDEZ_MINIMA = 0.0 # Umbral para la alerta de Cash Flow\n",
        "TASA_IVA_GENERAL = 0.19\n",
        "TASA_IMPUESTO_RENTA = 0.35\n",
        "TASA_RETENCION_FUENTE = 0.025\n",
        "TASA_ROTACION_CARTERA_DIAS = 30 # Días de rotación de cartera\n",
        "HORIZONTE_PROYECCION_DEFAULT = 12 # Meses de proyección por defecto\n",
        "NUM_SIMULACIONES_DEFAULT = 5000 # Número de simulaciones de Monte Carlo\n",
        "\n",
        "# Factores Ambientales (Para Huella de Carbono)\n",
        "EF_COMBUSTIBLE = 2.68  # Kg CO2e/L\n",
        "EF_ELECTRICO = 0.20    # Kg CO2e/kWh\n",
        "DIAS_TRABAJO_ANUAL = 240 # Para cálculo de Indicadores HSEQ\n",
        "\n",
        "MODULOS = [\n",
        "    \"Dashboard General\",\n",
        "    \"Módulo Gobernanza y Dueños\",\n",
        "    \"Módulo Financiero\",\n",
        "    \"Módulo Sostenibilidad Social RRHH\",\n",
        "    \"Módulo Sostenibilidad Ambiental\",\n",
        "    \"Módulo Riesgos HSEQ\",\n",
        "    \"Módulo Comercial\",\n",
        "    \"Módulo Operativo (Productividad)\"\n",
        "]\n",
        "\n",
        "# ==============================================================================\n",
        "# 2. AUTENTICACIÓN Y SEGURIDAD (Simulación)\n",
        "# ==============================================================================\n",
        "\n",
        "def check_password():\n",
        "    \"\"\"Retorna `True` si el usuario ingresó la contraseña correcta.\"\"\"\n",
        "\n",
        "    def password_entered():\n",
        "        \"\"\"Verifica si la contraseña es correcta.\"\"\"\n",
        "        if (st.session_state[\"username\"] == \"usuario_demo\" and\n",
        "            st.session_state[\"password\"] == \"demo360\"):\n",
        "            st.session_state[\"password_correct\"] = True\n",
        "            del st.session_state[\"password\"]  # Eliminar para seguridad\n",
        "            del st.session_state[\"username\"]\n",
        "        else:\n",
        "            st.session_state[\"password_correct\"] = False\n",
        "\n",
        "    if \"password_correct\" not in st.session_state:\n",
        "        # Primera ejecución, muestra la entrada de contraseña.\n",
        "        st.title(\"🌊 Horizonte Empresarial 360\")\n",
        "        st.info(\"Acceso restringido. Por favor, ingrese sus credenciales.\")\n",
        "        col1, col2 = st.columns(2)\n",
        "        with col1:\n",
        "            st.text_input(\"Usuario\", key=\"username\")\n",
        "        with col2:\n",
        "            st.text_input(\"Contraseña\", type=\"password\", on_change=password_entered, key=\"password\")\n",
        "        return False\n",
        "    elif not st.session_state[\"password_correct\"]:\n",
        "        # Contraseña incorrecta, muestra el mensaje de error.\n",
        "        st.error(\"😕 Usuario o Contraseña incorrectos.\")\n",
        "        col1, col2 = st.columns(2)\n",
        "        with col1:\n",
        "            st.text_input(\"Usuario\", key=\"username\")\n",
        "        with col2:\n",
        "            st.text_input(\"Contraseña\", type=\"password\", on_change=password_entered, key=\"password\")\n",
        "        return False\n",
        "    else:\n",
        "        # Contraseña correcta.\n",
        "        return True\n",
        "\n",
        "# ==============================================================================\n",
        "# 3. CARGA DE DATOS Y PRE-PROCESAMIENTO\n",
        "# ==============================================================================\n",
        "\n",
        "@st.cache_data\n",
        "def load_data_from_upload(uploaded_files: List[Any]) -> Dict[str, pd.DataFrame]:\n",
        "    \"\"\"Carga y pre-procesa todos los DataFrames necesarios desde archivos XLSX.\"\"\"\n",
        "\n",
        "    # Mapeo de nombre de hoja a variable de sesión y nombre de columna de FECHA\n",
        "    data_map_sheet_to_info = {\n",
        "        'financiero': {'var': 'df_financiero', 'date_col': 'FECHA'},\n",
        "        'comercial': {'var': 'df_comercial', 'date_col': 'FECHA_TRANSACCION'},\n",
        "        'rrhh_social': {'var': 'df_rrhh', 'date_col': 'FECHA'},\n",
        "        'sostenibilidad': {'var': 'df_sostenibilidad', 'date_col': 'Fecha_Reporte'},\n",
        "        'riesgos_hseq': {'var': 'df_riesgos', 'date_col': 'FECHA'},\n",
        "        'productividad': {'var': 'df_operativo', 'date_col': 'FECHA'}, # Asumiendo 'productividad' es el nombre de la hoja\n",
        "    }\n",
        "\n",
        "    loaded_data = {}\n",
        "    st.sidebar.markdown(\"---\")\n",
        "    st.sidebar.subheader(\"Estado de Carga de Datos\")\n",
        "\n",
        "    for file in uploaded_files:\n",
        "        try:\n",
        "            xls = pd.ExcelFile(file)\n",
        "            for sheet_name in xls.sheet_names:\n",
        "                map_info = None\n",
        "                # Buscar la información de mapeo para el nombre de la hoja (insensible a mayúsculas/minúsculas)\n",
        "                for k, v in data_map_sheet_to_info.items():\n",
        "                    if k.lower() == sheet_name.lower():\n",
        "                        map_info = v\n",
        "                        break\n",
        "\n",
        "                if map_info is None:\n",
        "                    st.sidebar.info(f\"⏭️ Saltando hoja '{sheet_name}' en '{file.name}' (no reconocida o no necesaria).\")\n",
        "                    continue\n",
        "\n",
        "                df = pd.read_excel(xls, sheet_name=sheet_name)\n",
        "\n",
        "                # Conversión de fechas\n",
        "                if map_info['date_col'] in df.columns:\n",
        "                    df[map_info['date_col']] = pd.to_datetime(df[map_info['date_col']], errors='coerce')\n",
        "\n",
        "                # Renombrar columna de fecha a un estándar 'FECHA' para consistencia\n",
        "                df.rename(columns={map_info['date_col']: 'FECHA'}, inplace=True)\n",
        "\n",
        "                # Pre-procesamiento específico\n",
        "                if map_info['var'] == 'df_comercial':\n",
        "                    df['Ingreso_Total'] = df['Volumen_Vendido'] * df['Precio_Unitario_Real']\n",
        "                    df['Costo_Total'] = df['Volumen_Vendido'] * df['Costo_Venta_Unitario']\n",
        "                    df['Margen_Bruto'] = df['Ingreso_Total'] - df['Costo_Total']\n",
        "\n",
        "                if map_info['var'] == 'df_sostenibilidad':\n",
        "                    # Calcular Huella de Carbono (Alcance 1: Combustible, Alcance 2: Electricidad)\n",
        "                    df['CO2e_Combustible'] = df['Consumo_Combustible_ACPM'] * EF_COMBUSTIBLE\n",
        "                    df['CO2e_Electrico'] = df['Consumo_Electrico_kWh'] * EF_ELECTRICO\n",
        "                    df['Huella_CO2e_Total'] = df['CO2e_Combustible'] + df['CO2e_Electrico']\n",
        "\n",
        "                if map_info['var'] == 'df_riesgos':\n",
        "                    # Calcular Costo Total por Evento HSEQ\n",
        "                    df.rename(columns={'Costo_Total_Evento': 'Costo_Total_Accidente'}, inplace=True)\n",
        "\n",
        "                if map_info['var'] == 'df_rrhh':\n",
        "                    # Calcular Costo por FTE (Full-Time Equivalent)\n",
        "                    df['Costo_x_FTE'] = df['Costo_Total_Nomina'] / df['FTEs_Promedio']\n",
        "\n",
        "                if map_info['var'] == 'df_operativo':\n",
        "                    # Calcular OEE (Overall Equipment Effectiveness) - Simplificado\n",
        "                    df['OEE_Teorico'] = (df['Unidades_Producidas'] / (df['Horas_Disponibles'] * (df['Unidades_Producidas'].mean() / df['Horas_Operadas'].mean()))).clip(upper=1.0)\n",
        "                    df['Tasa_Defectos'] = df['Unidades_Defectuosas'] / df['Unidades_Producidas']\n",
        "                    df['Costo_Total_Reproceso'] = df['Unidades_Defectuosas'] * df['Costo_Reproceso_Unit']\n",
        "\n",
        "                # Guardar el DataFrame\n",
        "                loaded_data[map_info['var']] = df\n",
        "                st.sidebar.success(f\"✅ Cargado: {map_info['var'].replace('df_', '').upper()} (desde hoja '{sheet_name}' de '{file.name}')\")\n",
        "\n",
        "        except Exception as e:\n",
        "            st.sidebar.error(f\"❌ Error al cargar/procesar el archivo '{file.name}' o alguna de sus hojas: {e}\")\n",
        "\n",
        "    # Verificar que todos los DataFrames requeridos estén presentes\n",
        "    required_dfs = ['df_financiero', 'df_comercial', 'df_rrhh', 'df_sostenibilidad', 'df_riesgos', 'df_operativo']\n",
        "    for df_name in required_dfs:\n",
        "        if df_name not in loaded_data:\n",
        "            loaded_data[df_name] = pd.DataFrame() # DataFrame vacío si falta\n",
        "\n",
        "    return loaded_data\n",
        "\n",
        "\n",
        "# ==============================================================================\n",
        "# 4. FUNCIONES DE CÁLCULO Y VISUALIZACIÓN POR MÓDULO\n",
        "# ==============================================================================\n",
        "\n",
        "# --- Módulo de Gobernanza y Dueños ---\n",
        "def display_gobernanza_module(all_dfs: Dict[str, pd.DataFrame]):\n",
        "    st.title(\"👑 Módulo Gobernanza y Dueños\")\n",
        "    st.subheader(\"Visión Estratégica y Health Score\")\n",
        "\n",
        "    df_financiero = all_dfs.get('df_financiero')\n",
        "    df_sostenibilidad = all_dfs.get('df_sostenibilidad')\n",
        "    df_riesgos = all_dfs.get('df_riesgos')\n",
        "    df_rrhh = all_dfs.get('df_rrhh')\n",
        "\n",
        "    st.markdown(\"\"\"\n",
        "        Este módulo consolida el rendimiento de la organización en un *Health Score* integral para la toma de decisiones al más alto nivel.\n",
        "    \"\"\")\n",
        "\n",
        "    # 1. Indicadores Clave de Desempeño (KPIs Consolidado)\n",
        "    st.subheader(\"Indicadores Clave Consolidados (Último Periodo)\")\n",
        "\n",
        "    if not df_financiero.empty and not df_sostenibilidad.empty and not df_riesgos.empty:\n",
        "        latest_date = df_financiero['FECHA'].max().strftime('%Y-%m')\n",
        "        st.caption(f\"Datos consolidados hasta: {latest_date}\")\n",
        "\n",
        "        # Indicador Financiero (Margen Neto Operativo Simplificado)\n",
        "        # Se asume que Ventas_Gravadas es proxy de Ingresos y Gastos_Gravados + Gasto_Nomina es proxy de Egresos Operativos\n",
        "        last_fin = df_financiero.loc[df_financiero['FECHA'].idxmax()]\n",
        "        ingresos = last_fin['Ventas_Gravadas']\n",
        "        egresos_operativos = last_fin['Gastos_Gravados'] + last_fin['Gasto_Nomina']\n",
        "        margen_neto_op = ingresos - egresos_operativos\n",
        "\n",
        "        # Indicador Ambiental (Cumplimiento)\n",
        "        num_incumplimientos = df_sostenibilidad['Incumplimientos_Vencidos'].sum()\n",
        "        max_posible_incumplimientos = df_sostenibilidad.shape[0] * 4 # Maximo 4 por mes (ejemplo)\n",
        "        cumplimiento_ambiental = 1 - (num_incumplimientos / max_posible_incumplimientos) if max_posible_incumplimientos > 0 else 1\n",
        "\n",
        "        # Indicador Social (Rotación)\n",
        "        avg_rotacion = df_rrhh['Tasa_Rotacion_Anual'].mean() / 100 # Promedio histórico\n",
        "\n",
        "        # Indicador Riesgos (Índice de Gravedad)\n",
        "        total_dias_perdidos = df_riesgos['Dias_Perdidos'].sum()\n",
        "        total_horas_trabajadas = df_riesgos['Horas_Trabajadas_Periodo'].sum()\n",
        "        indice_gravedad = (total_dias_perdidos / total_horas_trabajadas) * 240000\n",
        "\n",
        "        # Simulación de Health Score (0 a 100)\n",
        "        score_financiero = min(100, max(0, (margen_neto_op / (ingresos * 0.15)) * 50)) # Basado en 15% de margen como meta\n",
        "        score_ambiental = cumplimiento_ambiental * 100\n",
        "        score_social = min(100, max(0, (1 - (avg_rotacion / 0.18)) * 100)) # Basado en 18% de rotación como máximo\n",
        "        score_riesgos = min(100, max(0, (1 - (indice_gravedad / 50)) * 100)) # Basado en 50 como índice de gravedad máxima\n",
        "\n",
        "        health_score = (score_financiero * 0.35 + score_ambiental * 0.25 + score_social * 0.20 + score_riesgos * 0.20)\n",
        "\n",
        "        col1, col2, col3, col4, col5 = st.columns(5)\n",
        "\n",
        "        col1.metric(\"Ingresos Último Mes\", f\"COP {ingresos:,.0f}\", delta_color=\"normal\")\n",
        "        col2.metric(\"Margen Operativo\", f\"COP {margen_neto_op:,.0f}\", delta_color=\"normal\")\n",
        "        col3.metric(\"Huella CO2e Acumulada\", f\"{df_sostenibilidad['Huella_CO2e_Total'].sum():,.0f} Kg\", delta_color=\"inverse\")\n",
        "        col4.metric(\"Tasa de Rotación Anual (Promedio)\", f\"{avg_rotacion*100:.2f}%\", delta_color=\"inverse\")\n",
        "        col5.metric(\"Índice de Gravedad HSEQ\", f\"{indice_gravedad:.2f}\", delta_color=\"inverse\")\n",
        "\n",
        "        st.markdown(\"---\")\n",
        "        st.subheader(\"🎯 Health Score Empresarial 360\")\n",
        "        st.metric(\"Health Score General\", f\"{health_score:.1f}/100\",\n",
        "                  help=\"Índice ponderado basado en el rendimiento financiero, ambiental, social y de riesgos.\")\n",
        "\n",
        "        fig = go.Figure(go.Indicator(\n",
        "            mode = \"gauge+number\",\n",
        "            value = health_score,\n",
        "            domain = {'x': [0, 1], 'y': [0, 1]},\n",
        "            title = {'text': \"Health Score Empresarial\"},\n",
        "            gauge = {'axis': {'range': [None, 100], 'tickwidth': 1, 'tickcolor': \"darkblue\"},\n",
        "                     'bar': {'color': \"green\"},\n",
        "                     'steps': [\n",
        "                         {'range': [0, 50], 'color': \"red\"},\n",
        "                         {'range': [50, 75], 'color': \"yellow\"},\n",
        "                         {'range': [75, 100], 'color': \"green\"}],\n",
        "                     'threshold': {'line': {'color': \"red\", 'width': 4}, 'thickness': 0.75, 'value': 75}}))\n",
        "\n",
        "        st.plotly_chart(fig, use_container_width=True)\n",
        "    else:\n",
        "        st.warning(\"No hay datos cargados para generar el Health Score. Asegúrese de cargar todos los archivos requeridos.\")\n",
        "\n",
        "\n",
        "# --- Módulo Financiero ---\n",
        "def display_financiero_module(df_financiero: pd.DataFrame, HORIZONTE_PROYECCION: int, NUM_SIMULACIONES: int):\n",
        "    st.title(\"💰 Módulo Financiero: Gestión de Liquidez y Cash Flow\")\n",
        "    st.subheader(\"Proyección de Flujo de Caja (Cash Flow)\")\n",
        "\n",
        "    if df_financiero.empty:\n",
        "        st.warning(\"No se encontraron datos financieros. Por favor, cargue el archivo `financiero.xlsx`.\")\n",
        "        return\n",
        "\n",
        "    # 1. Configuración de Simulación\n",
        "    st.markdown(\"---\")\n",
        "    with st.expander(\"⚙️ Configuración de Escenarios de Proyección\"):\n",
        "        st.info(\"La proyección usa la media histórica y la desviación estándar de los flujos de caja (Cobros y Pagos) para simular el riesgo (Método Monte Carlo).\")\n",
        "        st.caption(\"Ajuste los parámetros del simulador:\")\n",
        "\n",
        "        # Inputs para el usuario\n",
        "        col1, col2 = st.columns(2)\n",
        "        with col1:\n",
        "            cobros_ajuste = st.number_input(\"Ajuste de Cobros (% sobre media histórica)\", min_value=-50, max_value=50, value=0, help=\"Ajusta la media de Cobros. Ej: 5 para un escenario optimista (+5%).\")\n",
        "        with col2:\n",
        "            pagos_ajuste = st.number_input(\"Ajuste de Pagos (% sobre media histórica)\", min_value=-50, max_value=50, value=0, help=\"Ajusta la media de Pagos. Ej: -5 para un escenario optimista en costos (-5%).\")\n",
        "\n",
        "    # 2. Análisis Histórico de Flujos\n",
        "    df_financiero = df_financiero.sort_values('FECHA').copy()\n",
        "    df_financiero['Flujo_Neto'] = df_financiero['Cobros_Clientes'] - (df_financiero['Pagos_Proveedores'] + df_financiero['Gasto_Nomina'])\n",
        "    df_financiero['Efectivo_Final'] = df_financiero['Efectivo_Inicial'].shift(-1).fillna(df_financiero['Efectivo_Inicial'] + df_financiero['Flujo_Neto'])\n",
        "\n",
        "    st.subheader(\"Análisis Histórico de Efectivo\")\n",
        "    col_hist1, col_hist2 = st.columns(2)\n",
        "    with col_hist1:\n",
        "        st.metric(\"Flujo Neto Promedio Mensual\", f\"COP {df_financiero['Flujo_Neto'].mean():,.0f}\")\n",
        "    with col_hist2:\n",
        "        st.metric(\"Efectivo Final (Último Periodo)\", f\"COP {df_financiero['Efectivo_Final'].iloc[-2]:,.0f}\") # -2 porque el último valor es el de inicio del siguiente\n",
        "\n",
        "    # Gráfico Histórico\n",
        "    fig_hist = px.line(df_financiero.tail(24), x='FECHA', y=['Cobros_Clientes', 'Pagos_Proveedores', 'Gasto_Nomina'],\n",
        "                       title='Tendencia Histórica de Flujos de Caja (Últimos 2 Años)',\n",
        "                       labels={'value': 'COP', 'FECHA': 'Fecha', 'variable': 'Tipo de Flujo'})\n",
        "    fig_hist.update_layout(hovermode=\"x unified\", legend_title_text='Flujo')\n",
        "    st.plotly_chart(fig_hist, use_container_width=True)\n",
        "\n",
        "    # 3. Simulación de Monte Carlo (Flujo de Caja Proyectado)\n",
        "\n",
        "    # Estadísticas para la simulación\n",
        "    flujo_neto_mean = df_financiero['Flujo_Neto'].mean()\n",
        "    flujo_neto_std = df_financiero['Flujo_Neto'].std()\n",
        "\n",
        "    # Ajuste de la media según el input del usuario\n",
        "    ajuste_factor = (1 + (cobros_ajuste / 100)) - (1 + (pagos_ajuste / 100))\n",
        "    flujo_neto_mean_ajustado = flujo_neto_mean * (1 + ajuste_factor / 2) # Ajuste simple\n",
        "\n",
        "\n",
        "    # Punto de partida de la simulación\n",
        "    start_date = df_financiero['FECHA'].max() + pd.DateOffset(months=1)\n",
        "    effective_start_cash = df_financiero['Efectivo_Final'].iloc[-1] # Efectivo final del último mes registrado\n",
        "\n",
        "    st.subheader(f\"Simulación de {NUM_SIMULACIONES} Escenarios a {HORIZONTE_PROYECCION} Meses\")\n",
        "\n",
        "    try:\n",
        "        simulations = []\n",
        "        for _ in range(NUM_SIMULACIONES):\n",
        "            # Generar variaciones mensuales (Normal Distribution)\n",
        "            monthly_flows = np.random.normal(loc=flujo_neto_mean_ajustado, scale=flujo_neto_std, size=HORIZONTE_PROYECCION)\n",
        "\n",
        "            # Calcular el flujo acumulado\n",
        "            cash_flow_projection = [effective_start_cash]\n",
        "            for flow in monthly_flows:\n",
        "                cash_flow_projection.append(cash_flow_projection[-1] + flow)\n",
        "\n",
        "            simulations.append(cash_flow_projection[1:])\n",
        "\n",
        "        df_sim = pd.DataFrame(simulations).T\n",
        "        df_sim.columns = [f'Sim_{i+1}' for i in range(NUM_SIMULACIONES)]\n",
        "\n",
        "        # Creación de fechas de proyección\n",
        "        projected_dates = [start_date + pd.DateOffset(months=i) for i in range(HORIZONTE_PROYECCION)]\n",
        "        df_sim['FECHA'] = projected_dates\n",
        "        df_sim = df_sim.set_index('FECHA')\n",
        "\n",
        "        # Cálculo de percentiles\n",
        "        df_sim['Media'] = df_sim.mean(axis=1)\n",
        "        df_sim['P5'] = df_sim.quantile(0.05, axis=1)  # Escenario Pesimista\n",
        "        df_sim['P95'] = df_sim.quantile(0.95, axis=1) # Escenario Optimista\n",
        "\n",
        "        # Gráfico de Proyección\n",
        "        fig_proj = go.Figure()\n",
        "\n",
        "        # Bandas de confianza (Percentiles 5 y 95)\n",
        "        fig_proj.add_trace(go.Scatter(x=df_sim.index, y=df_sim['P95'], fill=None, mode='lines',\n",
        "                                      line_color='rgba(0,176,246,0.3)', name='Percentil 95% (Optimista)'))\n",
        "        fig_proj.add_trace(go.Scatter(x=df_sim.index, y=df_sim['P5'], fill='tonexty', mode='lines',\n",
        "                                      line_color='rgba(255,160,0,0.3)', name='Percentil 5% (Pesimista)'))\n",
        "\n",
        "        # Línea de Media\n",
        "        fig_proj.add_trace(go.Scatter(x=df_sim.index, y=df_sim['Media'], mode='lines',\n",
        "                                      line=dict(color='blue', width=2), name='Proyección Media'))\n",
        "\n",
        "        # Umbral de Liquidez Mínima\n",
        "        fig_proj.add_hline(y=UMBRAL_LIQUIDEZ_MINIMA, line_width=2, line_dash=\"dash\", line_color=\"red\",\n",
        "                           annotation_text=f\"Umbral de Alerta ({UMBRAL_LIQUIDEZ_MINIMA:,.0f} COP)\", annotation_position=\"bottom right\")\n",
        "\n",
        "        fig_proj.update_layout(title=f'Proyección de Efectivo Final a {HORIZONTE_PROYECCION} Meses',\n",
        "                               yaxis_title='Efectivo (COP)', xaxis_title='Mes de Proyección',\n",
        "                               hovermode=\"x unified\")\n",
        "        st.plotly_chart(fig_proj, use_container_width=True)\n",
        "\n",
        "        # 4. Conclusión de Riesgo\n",
        "        risk_months = df_sim[df_sim['P5'] <= UMBRAL_LIQUIDEZ_MINIMA].shape[0]\n",
        "        if risk_months > 0:\n",
        "            st.error(f\"🚨 ALERTA DE RIESGO: El Escenario Pesimista (P5) predice que el Efectivo Final caerá por debajo del umbral de liquidez mínima (COP {UMBRAL_LIQUIDEZ_MINIMA:,.0f}) en {risk_months} de los {HORIZONTE_PROYECCION} meses proyectados. Se recomienda aplicar estrategias de gestión de capital de trabajo y cobranza.\")\n",
        "        else:\n",
        "            st.success(\"✅ La proyección de liquidez es saludable. El Escenario Pesimista (P5) se mantiene por encima del umbral de alerta.\")\n",
        "\n",
        "    except Exception as e:\n",
        "        st.error(f\"Error al ejecutar la simulación de Monte Carlo: {e}\")\n",
        "        st.info(\"Asegúrese de que las columnas `Cobros_Clientes`, `Pagos_Proveedores`, y `Gasto_Nomina` sean numéricas y no contengan valores nulos significativos.\")\n",
        "\n",
        "    # 5. Descarga de Reporte\n",
        "    st.markdown(\"---\")\n",
        "    def create_pdf_report(df: pd.DataFrame) -> BytesIO:\n",
        "        \"\"\"Simulación de generación de reporte PDF (usa CSV como placeholder).\"\"\"\n",
        "        output = BytesIO()\n",
        "        # En una aplicación real, usarías ReportLab o FPDF para generar un PDF.\n",
        "        # Aquí, generamos el DF de simulación como CSV para la descarga.\n",
        "        df.to_csv(output, index=True)\n",
        "        output.seek(0)\n",
        "        return output\n",
        "\n",
        "    if 'df_sim' in locals():\n",
        "        report_buffer = create_pdf_report(df_sim[['Media', 'P5', 'P95']])\n",
        "        st.download_button(\n",
        "            label=\"Descargar Reporte de Proyección Financiera (CSV)\",\n",
        "            data=report_buffer,\n",
        "            file_name=\"Reporte_Proyeccion_Cash_Flow.csv\",\n",
        "            mime=\"text/csv\"\n",
        "        )\n",
        "\n",
        "# --- Módulo de Sostenibilidad Social RRHH ---\n",
        "def display_rrhh_module(df_rrhh: pd.DataFrame):\n",
        "    st.title(\"👨‍👩‍👧‍👦 Módulo Sostenibilidad Social y RRHH\")\n",
        "\n",
        "    if df_rrhh.empty:\n",
        "        st.warning(\"No se encontraron datos de RRHH. Por favor, cargue el archivo `rrhh_social.xlsx`.\")\n",
        "        return\n",
        "\n",
        "    # 1. Indicadores Clave\n",
        "    st.subheader(\"Indicadores Clave de Talento\")\n",
        "\n",
        "    latest_date = df_rrhh['FECHA'].max()\n",
        "    latest_data = df_rrhh[df_rrhh['FECHA'] == latest_date].iloc[0]\n",
        "\n",
        "    col1, col2, col3, col4 = st.columns(4)\n",
        "    col1.metric(\"FTEs Promedio (Último Periodo)\", f\"{latest_data['FTEs_Promedio']:.1f}\")\n",
        "    col2.metric(\"Tasa de Rotación Anual\", f\"{latest_data['Tasa_Rotacion_Anual']:.2f}%\", delta_color=\"inverse\")\n",
        "    col3.metric(\"Costo por FTE (Último Periodo)\", f\"COP {latest_data['Costo_x_FTE']:,.0f}\")\n",
        "    col4.metric(\"Inversión en Capacitación (Acumulada)\", f\"COP {df_rrhh['Inversion_Capacitacion'].sum():,.0f}\")\n",
        "\n",
        "    # 2. Análisis de Tendencia\n",
        "    st.subheader(\"Tendencia de Rotación vs. Inversión en Capacitación\")\n",
        "\n",
        "    fig1 = px.line(df_rrhh.sort_values('FECHA'), x='FECHA', y='Tasa_Rotacion_Anual',\n",
        "                   title='Tasa de Rotación Anual por Mes',\n",
        "                   labels={'Tasa_Rotacion_Anual': 'Tasa de Rotación (%)', 'FECHA': 'Fecha'})\n",
        "    st.plotly_chart(fig1, use_container_width=True)\n",
        "\n",
        "    fig2 = px.bar(df_rrhh.sort_values('FECHA'), x='FECHA', y='Inversion_Capacitacion',\n",
        "                  title='Inversión Mensual en Capacitación',\n",
        "                  labels={'Inversion_Capacitacion': 'Inversión (COP)', 'FECHA': 'Fecha'})\n",
        "    st.plotly_chart(fig2, use_container_width=True)\n",
        "\n",
        "    # 3. Distribución de Costo por FTE\n",
        "    st.subheader(\"Distribución de Costo Total de Nómina\")\n",
        "\n",
        "    fig3 = px.histogram(df_rrhh, x='Costo_x_FTE', nbins=20,\n",
        "                        title='Distribución de Costo por FTE a lo largo del tiempo',\n",
        "                        labels={'Costo_x_FTE': 'Costo por FTE (COP)'})\n",
        "    st.plotly_chart(fig3, use_container_width=True)\n",
        "\n",
        "\n",
        "# --- Módulo de Sostenibilidad Ambiental ---\n",
        "def display_sostenibilidad_ambiental_module(df_sostenibilidad: pd.DataFrame):\n",
        "    st.title(\"🌳 Módulo Sostenibilidad Ambiental\")\n",
        "    st.subheader(\"Monitoreo de Huella y Cumplimiento\")\n",
        "\n",
        "    if df_sostenibilidad.empty:\n",
        "        st.warning(\"No se encontraron datos de Sostenibilidad Ambiental. Por favor, cargue el archivo `sostenibilidad.xlsx`.\")\n",
        "        return\n",
        "\n",
        "    df = df_sostenibilidad.sort_values('FECHA').copy()\n",
        "\n",
        "    # 1. Indicadores Clave\n",
        "    st.subheader(\"Métricas de Impacto Ambiental\")\n",
        "\n",
        "    total_co2 = df['Huella_CO2e_Total'].sum()\n",
        "    total_agua = df['Consumo_Agua_Total_m3'].sum()\n",
        "    total_residuos = df['Kg_Residuos_Solidos'].sum()\n",
        "    total_multa = df['Costo_Multa_Ambiental'].sum()\n",
        "\n",
        "    col1, col2, col3, col4 = st.columns(4)\n",
        "    col1.metric(\"Huella CO2e Total (Kg)\", f\"{total_co2:,.0f}\", delta_color=\"inverse\")\n",
        "    col2.metric(\"Consumo Agua Total (m³)\", f\"{total_agua:,.0f} m³\", delta_color=\"inverse\")\n",
        "    col3.metric(\"Residuos Sólidos (Kg)\", f\"{total_residuos:,.0f} Kg\", delta_color=\"inverse\")\n",
        "    col4.metric(\"Costo Acumulado Multas\", f\"COP {total_multa:,.0f}\", delta_color=\"inverse\")\n",
        "\n",
        "    # 2. Huella de Carbono por Alcance (Gráfico de torta/sol)\n",
        "    st.subheader(\"Huella de Carbono (Alcance 1 y 2)\")\n",
        "\n",
        "    co2_alcance = pd.DataFrame({\n",
        "        'Alcance': ['Alcance 1 (Combustible)', 'Alcance 2 (Electricidad)'],\n",
        "        'CO2e': [df['CO2e_Combustible'].sum(), df['CO2e_Electrico'].sum()]\n",
        "    })\n",
        "\n",
        "    fig_co2 = px.pie(co2_alcance, values='CO2e', names='Alcance',\n",
        "                     title='Distribución de Huella de Carbono (Kg CO2e)',\n",
        "                     color_discrete_sequence=px.colors.sequential.Agsunset)\n",
        "    st.plotly_chart(fig_co2, use_container_width=True)\n",
        "\n",
        "    # 3. Tendencia de Consumos Críticos\n",
        "    st.subheader(\"Tendencia de Consumos y Descargas de DBO5\")\n",
        "\n",
        "    fig_cons = px.line(df, x='FECHA', y=['Consumo_Combustible_ACPM', 'Consumo_Electrico_kWh', 'Consumo_Agua_Total_m3'],\n",
        "                       title='Consumo de Recursos (Mensual)',\n",
        "                       labels={'value': 'Unidad de Consumo', 'variable': 'Recurso', 'FECHA': 'Fecha'})\n",
        "    fig_cons.add_trace(go.Bar(x=df['FECHA'], y=df['Descarga_DBO5_Kg'], name='Descarga DBO5 (Kg)', yaxis='y2', opacity=0.3))\n",
        "\n",
        "    fig_cons.update_layout(yaxis=dict(title=\"Consumo (L/kWh/m³)\", side=\"left\"),\n",
        "                           yaxis2=dict(title=\"DBO5 (Kg)\", overlaying=\"y\", side=\"right\"),\n",
        "                           legend=dict(orientation=\"h\", yanchor=\"bottom\", y=1.02, xanchor=\"right\", x=1))\n",
        "    st.plotly_chart(fig_cons, use_container_width=True)\n",
        "\n",
        "    # 4. Impacto Financiero de Incumplimiento\n",
        "    st.subheader(\"Costo de Multas y Número de Incumplimientos Vencidos\")\n",
        "\n",
        "    fig_multa = px.bar(df, x='FECHA', y='Costo_Multa_Ambiental',\n",
        "                       title='Costo Mensual por Multas Ambientales',\n",
        "                       labels={'Costo_Multa_Ambiental': 'Costo (COP)', 'FECHA': 'Fecha'})\n",
        "    fig_multa.add_trace(go.Scatter(x=df['FECHA'], y=df['Incumplimientos_Vencidos'], mode='lines+markers',\n",
        "                                   name='Incumplimientos Vencidos', yaxis='y2', line=dict(color='red')))\n",
        "\n",
        "    fig_multa.update_layout(yaxis=dict(title=\"Costo Multa (COP)\", side=\"left\"),\n",
        "                           yaxis2=dict(title=\"Incumplimientos Vencidos\", overlaying=\"y\", side=\"right\"),\n",
        "                           hovermode=\"x unified\")\n",
        "    st.plotly_chart(fig_multa, use_container_width=True)\n",
        "\n",
        "\n",
        "# --- Módulo Riesgos HSEQ ---\n",
        "def display_riesgos_hseq_module(df_riesgos: pd.DataFrame):\n",
        "    st.title(\"🚨 Módulo Riesgos HSEQ (Salud, Seguridad, Ambiente y Calidad)\")\n",
        "    st.subheader(\"Monitoreo de Incidentes y Cumplimiento Normativo\")\n",
        "\n",
        "    if df_riesgos.empty:\n",
        "        st.warning(\"No se encontraron datos de Riesgos HSEQ. Por favor, cargue el archivo `riesgos_hseq.xlsx`.\")\n",
        "        return\n",
        "\n",
        "    df = df_riesgos.sort_values('FECHA').copy()\n",
        "\n",
        "    # Cálculos HSEQ Clásicos (Tasa de Frecuencia y Severidad)\n",
        "    total_incidentes = df[df['Tipo_Evento'] == 'Accidente Laboral'].shape[0]\n",
        "    total_horas = df['Horas_Trabajadas_Periodo'].sum()\n",
        "    total_dias_perdidos = df['Dias_Perdidos'].sum()\n",
        "\n",
        "    # Tasa de Frecuencia (IF) = (Total Incidentes / Horas Trabajadas) * 240,000\n",
        "    indice_frecuencia = (total_incidentes / total_horas) * 240000 if total_horas > 0 else 0\n",
        "    # Tasa de Severidad (IS) = (Días Perdidos / Horas Trabajadas) * 240,000\n",
        "    indice_severidad = (total_dias_perdidos / total_horas) * 240000 if total_horas > 0 else 0\n",
        "\n",
        "    # 1. Indicadores Clave de Riesgo\n",
        "    st.subheader(\"Índices de Seguridad y Salud en el Trabajo\")\n",
        "\n",
        "    col1, col2, col3, col4 = st.columns(4)\n",
        "    col1.metric(\"Total Incidentes (Accidentes)\", f\"{total_incidentes:,}\")\n",
        "    col2.metric(\"Índice de Frecuencia (IF)\", f\"{indice_frecuencia:.2f}\", help=\"Incidentes por 240,000 horas hombre\")\n",
        "    col3.metric(\"Índice de Severidad (IS)\", f\"{indice_severidad:.2f}\", delta_color=\"inverse\", help=\"Días perdidos por 240,000 horas hombre\")\n",
        "    col4.metric(\"Costo Total Acumulado Incidentes\", f\"COP {df['Costo_Total_Accidente'].sum():,.0f}\", delta_color=\"inverse\")\n",
        "\n",
        "    # 2. Clasificación de Eventos\n",
        "    st.subheader(\"Distribución de Eventos de Riesgo\")\n",
        "\n",
        "    event_counts = df['Tipo_Evento'].value_counts().reset_index()\n",
        "    event_counts.columns = ['Tipo_Evento', 'Conteo']\n",
        "\n",
        "    fig_event = px.bar(event_counts, x='Tipo_Evento', y='Conteo',\n",
        "                       title='Conteo por Tipo de Evento (Accidente, Incumplimiento, No Conformidad)',\n",
        "                       labels={'Conteo': 'Número de Eventos', 'Tipo_Evento': 'Tipo de Evento'},\n",
        "                       color='Tipo_Evento', color_discrete_sequence=px.colors.qualitative.Bold)\n",
        "    st.plotly_chart(fig_event, use_container_width=True)\n",
        "\n",
        "    # 3. Cumplimiento Normativo (Checklist)\n",
        "    st.subheader(\"Estado de Cumplimiento de Checklists Normativos\")\n",
        "\n",
        "    cumplimiento = df['Estado_Checklist'].value_counts().reset_index()\n",
        "    cumplimiento.columns = ['Estado', 'Conteo']\n",
        "\n",
        "    fig_comp = px.pie(cumplimiento, values='Conteo', names='Estado',\n",
        "                      title='Porcentaje de Checklists HSEQ',\n",
        "                      color_discrete_map={'Cumplido': 'green', 'Pendiente': 'yellow', 'Vencido': 'red'})\n",
        "    st.plotly_chart(fig_comp, use_container_width=True)\n",
        "\n",
        "\n",
        "# --- Módulo Comercial ---\n",
        "def display_comercial_module(df_comercial: pd.DataFrame):\n",
        "    st.title(\"📈 Módulo Comercial: Gestión de Ventas y Margen\")\n",
        "\n",
        "    if df_comercial.empty:\n",
        "        st.warning(\"No se encontraron datos comerciales. Por favor, cargue el archivo `comercial.xlsx`.\")\n",
        "        return\n",
        "\n",
        "    # 1. Indicadores Clave\n",
        "    st.subheader(\"Métricas de Venta y Rentabilidad\")\n",
        "\n",
        "    total_ingresos = df_comercial['Ingreso_Total'].sum()\n",
        "    total_margen_bruto = df_comercial['Margen_Bruto'].sum()\n",
        "    margen_bruto_pct = (total_margen_bruto / total_ingresos) * 100 if total_ingresos > 0 else 0\n",
        "\n",
        "    col1, col2, col3, col4 = st.columns(4)\n",
        "    col1.metric(\"Ingreso Total (Acumulado)\", f\"COP {total_ingresos:,.0f}\")\n",
        "    col2.metric(\"Margen Bruto Total\", f\"COP {total_margen_bruto:,.0f}\")\n",
        "    col3.metric(\"Margen Bruto (%)\", f\"{margen_bruto_pct:.2f}%\")\n",
        "    col4.metric(\"Total de Transacciones\", f\"{df_comercial.shape[0]:,}\")\n",
        "\n",
        "    # 2. Análisis Temporal de Margen\n",
        "    df_mensual = df_comercial.set_index('FECHA').resample('M').agg({\n",
        "        'Ingreso_Total': 'sum',\n",
        "        'Margen_Bruto': 'sum',\n",
        "        'Volumen_Vendido': 'sum'\n",
        "    }).reset_index()\n",
        "    df_mensual['Margen_Bruto_Pct'] = (df_mensual['Margen_Bruto'] / df_mensual['Ingreso_Total']) * 100\n",
        "\n",
        "    st.subheader(\"Tendencia de Margen Bruto Mensual\")\n",
        "    fig1 = px.area(df_mensual, x='FECHA', y='Margen_Bruto_Pct',\n",
        "                   title='Margen Bruto Porcentual a lo largo del Tiempo',\n",
        "                   labels={'Margen_Bruto_Pct': 'Margen Bruto (%)', 'FECHA': 'Fecha'})\n",
        "    st.plotly_chart(fig1, use_container_width=True)\n",
        "\n",
        "    # 3. Top 10 Productos por Margen\n",
        "    st.subheader(\"Top 10 Productos por Margen Bruto\")\n",
        "    top_productos = df_comercial.groupby('Producto_ID')['Margen_Bruto'].sum().nlargest(10).reset_index()\n",
        "\n",
        "    fig2 = px.bar(top_productos, x='Margen_Bruto', y='Producto_ID', orientation='h',\n",
        "                  title='Top 10 Productos por Margen Bruto Acumulado',\n",
        "                  labels={'Margen_Bruto': 'Margen Bruto (COP)', 'Producto_ID': 'ID Producto'})\n",
        "    fig2.update_yaxes(categoryorder='total ascending')\n",
        "    st.plotly_chart(fig2, use_container_width=True)\n",
        "\n",
        "\n",
        "# --- Módulo Operativo (Productividad/Procesos) ---\n",
        "def display_operativo_module(df_operativo: pd.DataFrame):\n",
        "    st.title(\"🏭 Módulo Operativo (Productividad y Procesos)\")\n",
        "\n",
        "    if df_operativo.empty:\n",
        "        st.warning(\"No se encontraron datos operativos. Por favor, cargue el archivo `productividad.xlsx`.\")\n",
        "        return\n",
        "\n",
        "    # 1. Indicadores Clave\n",
        "    st.subheader(\"Métricas de Eficiencia de Producción\")\n",
        "\n",
        "    # Métricas Operativas\n",
        "    avg_oee = df_operativo['OEE_Teorico'].mean() * 100\n",
        "    avg_tasa_defectos = df_operativo['Tasa_Defectos'].mean() * 100\n",
        "    total_costo_reproceso = df_operativo['Costo_Total_Reproceso'].sum()\n",
        "\n",
        "    col1, col2, col3, col4 = st.columns(4)\n",
        "    col1.metric(\"OEE Promedio (Teórico)\", f\"{avg_oee:.2f}%\", delta_color=\"normal\", help=\"Eficiencia General del Equipo - Simplificado.\")\n",
        "    col2.metric(\"Tasa Promedio de Defectos\", f\"{avg_tasa_defectos:.2f}%\", delta_color=\"inverse\")\n",
        "    col3.metric(\"Costo Acumulado de Reproceso\", f\"COP {total_costo_reproceso:,.0f}\", delta_color=\"inverse\")\n",
        "    col4.metric(\"Horas Operadas Totales\", f\"{df_operativo['Horas_Operadas'].sum():,.0f} h\")\n",
        "\n",
        "    # 2. OEE y Tasa de Defectos\n",
        "    st.subheader(\"Tendencia de Eficiencia y Calidad\")\n",
        "\n",
        "    df_operativo['Mes_Año'] = df_operativo['FECHA'].dt.to_period('M').astype(str)\n",
        "\n",
        "    fig1 = go.Figure()\n",
        "    fig1.add_trace(go.Scatter(x=df_operativo['Mes_Año'], y=df_operativo['OEE_Teorico'] * 100, mode='lines+markers', name='OEE (%)', yaxis='y1'))\n",
        "    fig1.add_trace(go.Scatter(x=df_operativo['Mes_Año'], y=df_operativo['Tasa_Defectos'] * 100, mode='lines+markers', name='Tasa de Defectos (%)', yaxis='y2', line=dict(color='red')))\n",
        "\n",
        "    fig1.update_layout(\n",
        "        title='OEE y Tasa de Defectos a lo Largo del Tiempo',\n",
        "        xaxis_title='Fecha',\n",
        "        yaxis=dict(title=\"OEE (%)\", side=\"left\", range=[0, 100]),\n",
        "        yaxis2=dict(title=\"Tasa de Defectos (%)\", overlaying=\"y\", side=\"right\", range=[0, df_operativo['Tasa_Defectos'].max()*100*1.1])\n",
        "    )\n",
        "    st.plotly_chart(fig1, use_container_width=True)\n",
        "\n",
        "\n",
        "    # 3. Reproceso vs. Costo\n",
        "    st.subheader(\"Costo de Reproceso vs. Unidades Defectuosas\")\n",
        "\n",
        "    fig2 = px.scatter(df_operativo, x='Unidades_Defectuosas', y='Costo_Total_Reproceso',\n",
        "                      size='Costo_Mano_Obra_Hora', color='Planta_ID', hover_name='FECHA',\n",
        "                      title='Relación entre Defectos y Costo de Reproceso (Tamaño: Costo Mano de Obra)')\n",
        "    st.plotly_chart(fig2, use_container_width=True)\n",
        "\n",
        "# --- Dashboard General ---\n",
        "def display_dashboard(all_dfs: Dict[str, pd.DataFrame]):\n",
        "    st.title(\"🌐 Dashboard General: Visión 360\")\n",
        "    st.subheader(\"Resumen de Métricas Clave de la Plataforma\")\n",
        "\n",
        "    st.markdown(\"\"\"\n",
        "        Este dashboard ofrece una perspectiva de alto nivel del rendimiento de **Acuamar S.A.**,\n",
        "        consolidando los KPIs más críticos de los 7 módulos.\n",
        "    \"\"\")\n",
        "\n",
        "    # Extraer métricas clave para el Dashboard\n",
        "    metrics = {}\n",
        "\n",
        "    # Módulo Financiero\n",
        "    df_financiero = all_dfs.get('df_financiero')\n",
        "    if not df_financiero.empty:\n",
        "        last_fin = df_financiero.loc[df_financiero['FECHA'].idxmax()]\n",
        "        ingresos = last_fin['Ventas_Gravadas']\n",
        "        egresos_operativos = last_fin['Gastos_Gravados'] + last_fin['Gasto_Nomina']\n",
        "        metrics['Margen_Neto_Op'] = ingresos - egresos_operativos\n",
        "        metrics['Efectivo_Final'] = df_financiero['Efectivo_Inicial'].iloc[-1]\n",
        "\n",
        "    # Módulo Comercial\n",
        "    df_comercial = all_dfs.get('df_comercial')\n",
        "    if not df_comercial.empty:\n",
        "        total_ingresos = df_comercial['Ingreso_Total'].sum()\n",
        "        total_margen_bruto = df_comercial['Margen_Bruto'].sum()\n",
        "        metrics['Margen_Bruto_Pct'] = (total_margen_bruto / total_ingresos) * 100 if total_ingresos > 0 else 0\n",
        "\n",
        "    # Módulo Social (RRHH)\n",
        "    df_rrhh = all_dfs.get('df_rrhh')\n",
        "    if not df_rrhh.empty:\n",
        "        metrics['Rotacion_Anual'] = df_rrhh['Tasa_Rotacion_Anual'].iloc[-1]\n",
        "        metrics['FTEs'] = df_rrhh['FTEs_Promedio'].iloc[-1]\n",
        "\n",
        "    # Módulo Ambiental\n",
        "    df_sostenibilidad = all_dfs.get('df_sostenibilidad')\n",
        "    if not df_sostenibilidad.empty:\n",
        "        metrics['Huella_CO2e_Total'] = df_sostenibilidad['Huella_CO2e_Total'].sum()\n",
        "        metrics['Costo_Multas'] = df_sostenibilidad['Costo_Multa_Ambiental'].sum()\n",
        "\n",
        "    # Módulo Riesgos HSEQ\n",
        "    df_riesgos = all_dfs.get('df_riesgos')\n",
        "    if not df_riesgos.empty:\n",
        "        total_incidentes = df_riesgos[df_riesgos['Tipo_Evento'] == 'Accidente Laboral'].shape[0]\n",
        "        total_horas = df_riesgos['Horas_Trabajadas_Periodo'].sum()\n",
        "        metrics['IF_HSEQ'] = (total_incidentes / total_horas) * 240000 if total_horas > 0 else 0\n",
        "\n",
        "    # Módulo Operativo\n",
        "    df_operativo = all_dfs.get('df_operativo')\n",
        "    if not df_operativo.empty:\n",
        "        metrics['OEE_Promedio'] = df_operativo['OEE_Teorico'].mean() * 100\n",
        "        metrics['Tasa_Defectos'] = df_operativo['Tasa_Defectos'].mean() * 100\n",
        "\n",
        "    # 1. Row de Indicadores de Alto Nivel\n",
        "    st.header(\"1. Rendimiento Global\")\n",
        "    col1, col2, col3, col4 = st.columns(4)\n",
        "    col1.metric(\"💰 Margen Neto Operativo\", f\"COP {metrics.get('Margen_Neto_Op', 0):,.0f}\", help=\"Ingresos - Egresos Operativos\")\n",
        "    col2.metric(\"📈 Margen Bruto Comercial (%)\", f\"{metrics.get('Margen_Bruto_Pct', 0):.2f}%\")\n",
        "    col3.metric(\"🏭 OEE Promedio\", f\"{metrics.get('OEE_Promedio', 0):.2f}%\", delta_color=\"normal\")\n",
        "    col4.metric(\"👨‍👩‍👧‍👦 Rotación Anual (Últ. Mes)\", f\"{metrics.get('Rotacion_Anual', 0):.2f}%\", delta_color=\"inverse\")\n",
        "\n",
        "    # 2. Row de Indicadores de Riesgo y Sostenibilidad\n",
        "    st.header(\"2. Riesgos y Sostenibilidad\")\n",
        "    col5, col6, col7, col8 = st.columns(4)\n",
        "    col5.metric(\"🚨 Índice Frecuencia HSEQ (IF)\", f\"{metrics.get('IF_HSEQ', 0):.2f}\", delta_color=\"inverse\")\n",
        "    col6.metric(\"🌳 Huella CO2e (Acumulada)\", f\"{metrics.get('Huella_CO2e_Total', 0):,.0f} Kg\", delta_color=\"inverse\")\n",
        "    col7.metric(\"💧 Costo Multas Ambientales\", f\"COP {metrics.get('Costo_Multas', 0):,.0f}\", delta_color=\"inverse\")\n",
        "    col8.metric(\"📉 Tasa Promedio de Defectos\", f\"{metrics.get('Tasa_Defectos', 0):.2f}%\", delta_color=\"inverse\")\n",
        "\n",
        "    # 3. Gráfico de Tendencia Integrada\n",
        "    st.header(\"3. Tendencias Financieras y Operativas\")\n",
        "\n",
        "    if not df_financiero.empty and not df_operativo.empty:\n",
        "        # Preparar datos para gráfico de línea dual\n",
        "        df_fin_mensual = df_financiero.set_index('FECHA')['Flujo_Neto'].resample('M').sum().reset_index()\n",
        "        df_op_mensual = df_operativo.set_index('FECHA')['OEE_Teorico'].resample('M').mean().reset_index()\n",
        "\n",
        "        df_merge = pd.merge(df_fin_mensual, df_op_mensual, on='FECHA', how='inner')\n",
        "\n",
        "        if not df_merge.empty:\n",
        "            fig_trend = go.Figure()\n",
        "\n",
        "            # Flujo Neto (Eje Y1)\n",
        "            fig_trend.add_trace(go.Bar(x=df_merge['FECHA'], y=df_merge['Flujo_Neto'], name='Flujo Neto (COP)', yaxis='y1', opacity=0.6))\n",
        "\n",
        "            # OEE (Eje Y2)\n",
        "            fig_trend.add_trace(go.Scatter(x=df_merge['FECHA'], y=df_merge['OEE_Teorico'] * 100, mode='lines+markers', name='OEE (%)', yaxis='y2', line=dict(color='green', width=3)))\n",
        "\n",
        "            fig_trend.update_layout(\n",
        "                title='Relación: Flujo Neto (Finanzas) vs. OEE (Operaciones)',\n",
        "                xaxis_title='Fecha',\n",
        "                yaxis=dict(title=\"Flujo Neto (COP)\", side=\"left\"),\n",
        "                yaxis2=dict(title=\"OEE (%)\", overlaying=\"y\", side=\"right\", range=[0, 100]),\n",
        "                legend=dict(orientation=\"h\", yanchor=\"bottom\", y=1.02, xanchor=\"right\", x=1)\n",
        "            )\n",
        "            st.plotly_chart(fig_trend, use_container_width=True)\n",
        "\n",
        "\n",
        "# ==============================================================================\n",
        "# 5. FLUJO PRINCIPAL DE LA APLICACIÓN\n",
        "# ==============================================================================\n",
        "\n",
        "if check_password():\n",
        "\n",
        "    # Carga de archivos al inicio de la sesión\n",
        "    if 'data_loaded' not in st.session_state:\n",
        "        st.session_state['data_loaded'] = False\n",
        "        st.session_state['dfs'] = {}\n",
        "        st.session_state['HORIZONTE_PROYECCION'] = HORIZONTE_PROYECCION_DEFAULT\n",
        "        st.session_state['NUM_SIMULACIONES'] = NUM_SIMULACIONES_DEFAULT\n",
        "\n",
        "    st.sidebar.markdown(\"---\")\n",
        "\n",
        "    # Sección de Carga de Archivos\n",
        "    with st.sidebar.expander(\"📂 Cargar Datos\"):\n",
        "        st.caption(\"Cargue todos los archivos .xlsx requeridos. Puede subir varios archivos Excel, y el sistema buscará las hojas correspondientes por nombre (financiero, comercial, rrhh_social, sostenibilidad, riesgos_hseq, productividad).\")\n",
        "        uploaded_files = st.file_uploader(\n",
        "            \"Arrastre y suelte los archivos .xlsx aquí\",\n",
        "            type=['xlsx'],\n",
        "            accept_multiple_files=True\n",
        "        )\n",
        "        if uploaded_files:\n",
        "            # Botón de carga y procesamiento (solo se ejecuta si hay archivos y no se ha cargado)\n",
        "            if st.button(\"Procesar Archivos Cargados\"):\n",
        "                st.session_state['dfs'] = load_data_from_upload(uploaded_files)\n",
        "                st.session_state['data_loaded'] = True\n",
        "                st.success(\"¡Datos cargados y pre-procesados con éxito!\")\n",
        "\n",
        "    # Placeholder de Conexión SQL\n",
        "    st.sidebar.markdown(\"---\")\n",
        "    st.sidebar.subheader(\"Conexión a Datos Vivos (Simulado)\")\n",
        "    st.sidebar.success(\"Estado: Conectado a SQL DB (Simulación)\")\n",
        "\n",
        "    st.sidebar.markdown(\"---\")\n",
        "    st.sidebar.subheader(\"Navegación por Módulos\")\n",
        "\n",
        "    # Selector de módulo en el sidebar\n",
        "    selected_module = st.sidebar.radio(\"Selecciona un Módulo\", MODULOS)\n",
        "\n",
        "    # Slider de Horizonte de Proyección para Módulos Predictivos\n",
        "    st.sidebar.markdown(\"---\")\n",
        "    st.session_state['HORIZONTE_PROYECCION'] = st.sidebar.slider(\n",
        "        \"Horizonte de Proyección (Meses)\",\n",
        "        min_value=3, max_value=24,\n",
        "        value=st.session_state['HORIZONTE_PROYECCION'],\n",
        "        step=1\n",
        "    )\n",
        "    st.session_state['NUM_SIMULACIONES'] = st.sidebar.slider(\n",
        "        \"Número de Simulaciones (Monte Carlo)\",\n",
        "        min_value=1000, max_value=10000,\n",
        "        value=st.session_state['NUM_SIMULACIONES'],\n",
        "        step=1000\n",
        "    )\n",
        "\n",
        "\n",
        "    # Contenido central basado en el módulo seleccionado\n",
        "    if not st.session_state['data_loaded']:\n",
        "        st.title(\"Bienvenido a Horizonte Empresarial 360\")\n",
        "        st.info(\"Por favor, cargue los archivos de datos en la sección 'Cargar Datos' del menú lateral para comenzar a navegar por los módulos.\")\n",
        "    else:\n",
        "        dfs = st.session_state['dfs']\n",
        "\n",
        "        if selected_module == \"Dashboard General\":\n",
        "            display_dashboard(dfs)\n",
        "\n",
        "        elif selected_module == \"Módulo Gobernanza y Dueños\":\n",
        "            display_gobernanza_module(dfs)\n",
        "\n",
        "        elif selected_module == \"Módulo Financiero\":\n",
        "            display_financiero_module(dfs['df_financiero'], st.session_state['HORIZONTE_PROYECCION'], st.session_state['NUM_SIMULACIONES'])\n",
        "\n",
        "        elif selected_module == \"Módulo Sostenibilidad Social RRHH\":\n",
        "            display_rrhh_module(dfs['df_rrhh'])\n",
        "\n",
        "        elif selected_module == \"Módulo Sostenibilidad Ambiental\":\n",
        "            display_sostenibilidad_ambiental_module(dfs['df_sostenibilidad'])\n",
        "\n",
        "        elif selected_module == \"Módulo Riesgos HSEQ\":\n",
        "            display_riesgos_hseq_module(dfs['df_riesgos'])\n",
        "\n",
        "        elif selected_module == \"Módulo Comercial\":\n",
        "            display_comercial_module(dfs['df_comercial'])\n",
        "\n",
        "        elif selected_module == \"Módulo Operativo (Productividad)\":\n",
        "            display_operativo_module(dfs['df_operativo'])"
      ],
      "outputs": [],
      "execution_count": null,
      "metadata": {
        "id": "XbcV3BZ_wKkm"
      }
    }
  ],
  "metadata": {
    "colab": {
      "provenance": [],
      "include_colab_link": true
    },
    "kernelspec": {
      "display_name": "Python 3",
      "name": "python3"
    }
  },
  "nbformat": 4,
  "nbformat_minor": 0
}